// Code generated by ent, DO NOT EDIT.

package memorynodeuser

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the memorynodeuser type in the database.
	Label = "memory_node_user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMemoryNodeID holds the string denoting the memory_node_id field in the database.
	FieldMemoryNodeID = "memory_node_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// EdgeMemoryNode holds the string denoting the memory_node edge name in mutations.
	EdgeMemoryNode = "memory_node"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the memorynodeuser in the database.
	Table = "memory_node_users"
	// MemoryNodeTable is the table that holds the memory_node relation/edge.
	MemoryNodeTable = "memory_node_users"
	// MemoryNodeInverseTable is the table name for the MemoryNode entity.
	// It exists in this package in order to avoid circular dependency with the "memorynode" package.
	MemoryNodeInverseTable = "memory_nodes"
	// MemoryNodeColumn is the table column denoting the memory_node relation/edge.
	MemoryNodeColumn = "memory_node_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "memory_node_users"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for memorynodeuser fields.
var Columns = []string{
	FieldID,
	FieldMemoryNodeID,
	FieldUserID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// MemoryNodeIDValidator is a validator for the "memory_node_id" field. It is called by the builders before save.
	MemoryNodeIDValidator func(int) error
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(int) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the MemoryNodeUser queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMemoryNodeID orders the results by the memory_node_id field.
func ByMemoryNodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemoryNodeID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByMemoryNodeField orders the results by memory_node field.
func ByMemoryNodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMemoryNodeStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newMemoryNodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MemoryNodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MemoryNodeTable, MemoryNodeColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
