// Code generated by ent, DO NOT EDIT.

package card

import (
	"arturgudiev/memoryguard/ent/schema"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the card type in the database.
	Label = "card"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldQuestion holds the string denoting the question field in the database.
	FieldQuestion = "question"
	// FieldAnswer holds the string denoting the answer field in the database.
	FieldAnswer = "answer"
	// FieldParentNodes holds the string denoting the parent_nodes field in the database.
	FieldParentNodes = "parent_nodes"
	// FieldUsed holds the string denoting the used field in the database.
	FieldUsed = "used"
	// FieldNeeded holds the string denoting the needed field in the database.
	FieldNeeded = "needed"
	// FieldCount holds the string denoting the count field in the database.
	FieldCount = "count"
	// FieldReverseCount holds the string denoting the reverse_count field in the database.
	FieldReverseCount = "reverse_count"
	// FieldUsageType holds the string denoting the usage_type field in the database.
	FieldUsageType = "usage_type"
	// FieldShared holds the string denoting the shared field in the database.
	FieldShared = "shared"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeUserCounts holds the string denoting the user_counts edge name in mutations.
	EdgeUserCounts = "user_counts"
	// EdgeCardUsers holds the string denoting the card_users edge name in mutations.
	EdgeCardUsers = "card_users"
	// Table holds the table name of the card in the database.
	Table = "cards"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "cards"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// UserCountsTable is the table that holds the user_counts relation/edge.
	UserCountsTable = "card_user_counts"
	// UserCountsInverseTable is the table name for the CardUserCount entity.
	// It exists in this package in order to avoid circular dependency with the "cardusercount" package.
	UserCountsInverseTable = "card_user_counts"
	// UserCountsColumn is the table column denoting the user_counts relation/edge.
	UserCountsColumn = "card_id"
	// CardUsersTable is the table that holds the card_users relation/edge.
	CardUsersTable = "card_users"
	// CardUsersInverseTable is the table name for the CardUser entity.
	// It exists in this package in order to avoid circular dependency with the "carduser" package.
	CardUsersInverseTable = "card_users"
	// CardUsersColumn is the table column denoting the card_users relation/edge.
	CardUsersColumn = "card_id"
)

// Columns holds all SQL columns for card fields.
var Columns = []string{
	FieldID,
	FieldQuestion,
	FieldAnswer,
	FieldParentNodes,
	FieldUsed,
	FieldNeeded,
	FieldCount,
	FieldReverseCount,
	FieldUsageType,
	FieldShared,
	FieldUserID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultQuestion holds the default value on creation for the "question" field.
	DefaultQuestion []int
	// DefaultAnswer holds the default value on creation for the "answer" field.
	DefaultAnswer []int
	// DefaultParentNodes holds the default value on creation for the "parent_nodes" field.
	DefaultParentNodes []int
	// DefaultUsed holds the default value on creation for the "used" field.
	DefaultUsed int
	// DefaultNeeded holds the default value on creation for the "needed" field.
	DefaultNeeded int
	// DefaultCount holds the default value on creation for the "count" field.
	DefaultCount int
	// DefaultReverseCount holds the default value on creation for the "reverse_count" field.
	DefaultReverseCount int
	// DefaultShared holds the default value on creation for the "shared" field.
	DefaultShared bool
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(int) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

const DefaultUsageType schema.UsageType = "common"

// UsageTypeValidator is a validator for the "usage_type" field enum values. It is called by the builders before save.
func UsageTypeValidator(ut schema.UsageType) error {
	switch ut.String() {
	case "active", "passive", "transitional", "common":
		return nil
	default:
		return fmt.Errorf("card: invalid enum value for usage_type field: %q", ut)
	}
}

// OrderOption defines the ordering options for the Card queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsed orders the results by the used field.
func ByUsed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsed, opts...).ToFunc()
}

// ByNeeded orders the results by the needed field.
func ByNeeded(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNeeded, opts...).ToFunc()
}

// ByCount orders the results by the count field.
func ByCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCount, opts...).ToFunc()
}

// ByReverseCount orders the results by the reverse_count field.
func ByReverseCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReverseCount, opts...).ToFunc()
}

// ByUsageType orders the results by the usage_type field.
func ByUsageType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageType, opts...).ToFunc()
}

// ByShared orders the results by the shared field.
func ByShared(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShared, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserCountsCount orders the results by user_counts count.
func ByUserCountsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserCountsStep(), opts...)
	}
}

// ByUserCounts orders the results by user_counts terms.
func ByUserCounts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserCountsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCardUsersCount orders the results by card_users count.
func ByCardUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCardUsersStep(), opts...)
	}
}

// ByCardUsers orders the results by card_users terms.
func ByCardUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCardUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newUserCountsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserCountsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UserCountsTable, UserCountsColumn),
	)
}
func newCardUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CardUsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CardUsersTable, CardUsersColumn),
	)
}
