// Code generated by ent, DO NOT EDIT.

package memorynode

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the memorynode type in the database.
	Label = "memory_node"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldChildren holds the string denoting the children field in the database.
	FieldChildren = "children"
	// FieldParents holds the string denoting the parents field in the database.
	FieldParents = "parents"
	// FieldCards holds the string denoting the cards field in the database.
	FieldCards = "cards"
	// FieldAliases holds the string denoting the aliases field in the database.
	FieldAliases = "aliases"
	// FieldPriorities holds the string denoting the priorities field in the database.
	FieldPriorities = "priorities"
	// FieldGroups holds the string denoting the groups field in the database.
	FieldGroups = "groups"
	// FieldShared holds the string denoting the shared field in the database.
	FieldShared = "shared"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the memorynode in the database.
	Table = "memory_nodes"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "memory_nodes"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for memorynode fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldChildren,
	FieldParents,
	FieldCards,
	FieldAliases,
	FieldPriorities,
	FieldGroups,
	FieldShared,
	FieldUserID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultChildren holds the default value on creation for the "children" field.
	DefaultChildren []int
	// DefaultParents holds the default value on creation for the "parents" field.
	DefaultParents []int
	// DefaultCards holds the default value on creation for the "cards" field.
	DefaultCards []int
	// DefaultAliases holds the default value on creation for the "aliases" field.
	DefaultAliases []string
	// DefaultShared holds the default value on creation for the "shared" field.
	DefaultShared bool
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(int) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the MemoryNode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByShared orders the results by the shared field.
func ByShared(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShared, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
