// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"arturgudiev/memoryguard/repositories"
	"arturgudiev/memoryguard/services"

	_ "github.com/lib/pq"
)

// Injectors from wire.go:

// InitializeApp creates App with all dependencies wired automatically.
func InitializeApp() (*App, error) {
	client, err := provideEntClient()
	if err != nil {
		return nil, err
	}
	usersRepository := repositories.NewUsersRepository(client)
	refreshTokensRepository := repositories.NewRefreshTokensRepository(client)
	memoryNodesRepository := repositories.NewMemoryNodesRepository(client)
	cardsRepository := repositories.NewCardsRepository(client)
	cardItemsRepository := repositories.NewCardItemsRepository(client)
	cardUserCountsRepository := repositories.NewCardUserCountsRepository(client)
	cardUsersRepository := repositories.NewCardUsersRepository(client)
	memoryNodeUsersRepository := repositories.NewMemoryNodeUsersRepository(client)
	memoryNodesService := services.NewMemoryNodesService(memoryNodesRepository, memoryNodeUsersRepository, cardsRepository, cardUsersRepository, cardUserCountsRepository, cardItemsRepository)
	cardItemsService := services.NewCardItemsService(cardItemsRepository)
	cardsService := services.NewCardsService(cardsRepository, cardItemsService, memoryNodesService, cardUserCountsRepository, cardUsersRepository)
	app := provideApp(client, usersRepository, refreshTokensRepository, memoryNodesRepository, cardsRepository, cardItemsRepository, cardUserCountsRepository, cardUsersRepository, memoryNodeUsersRepository, memoryNodesService, cardsService, cardItemsService)
	return app, nil
}
