// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"arturgudiev/memoryguard/ent"
	"arturgudiev/memoryguard/ent/migrate"
	"arturgudiev/memoryguard/ent/schema"
	"arturgudiev/memoryguard/repositories"
	"arturgudiev/memoryguard/services"
	"context"
	"log"
	"net/url"
	"os"
	"strings"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

// InitializeApp creates App with all dependencies wired automatically.
func InitializeApp() (*App, error) {
	client, err := provideEntClient()
	if err != nil {
		return nil, err
	}
	usersRepository := repositories.NewUsersRepository(client)
	refreshTokensRepository := repositories.NewRefreshTokensRepository(client)
	memoryNodesRepository := repositories.NewMemoryNodesRepository(client)
	cardsRepository := repositories.NewCardsRepository(client)
	cardItemsRepository := repositories.NewCardItemsRepository(client)
	memoryNodesService := services.NewMemoryNodesService(memoryNodesRepository)
	cardItemsService := services.NewCardItemsService(cardItemsRepository)
	cardsService := services.NewCardsService(cardsRepository, cardItemsService, memoryNodesService)
	app := provideApp(client, usersRepository, refreshTokensRepository, memoryNodesRepository, cardsRepository, cardItemsRepository, memoryNodesService, cardsService, cardItemsService)
	return app, nil
}

// wire.go:

func provideEntClient() (*ent.Client, error) {
	dbURL := os.Getenv("DATABASE_URL")
	if dbURL == "" {
		dbName := os.Getenv("DB_NAME")
		if dbName == "" {
			dbName = "memoryguard"
		}
		dbPassword := os.Getenv("DB_PASSWORD")
		if dbPassword == "" {
			dbPassword = "postgres"
		}
		dbHost := os.Getenv("DB_HOST")
		if dbHost == "" {
			dbHost = "localhost"
		}
		dbUser := os.Getenv("DB_USER")
		if dbUser == "" {
			dbUser = "postgres"
		}
		u := &url.URL{
			Scheme:   "postgres",
			User:     url.UserPassword(dbUser, dbPassword),
			Host:     dbHost,
			Path:     "/" + url.PathEscape(dbName),
			RawQuery: "sslmode=disable",
		}
		dbURL = u.String()
		log.Printf("DATABASE_URL was not set; using constructed DB URL: %s", dbURL)
	}

	client, err := ent.Open("postgres", dbURL)
	if err != nil {
		return nil, err
	}

	ctx := context.Background()
	if err := client.Schema.Create(ctx, migrate.WithDropColumn(true), migrate.WithDropIndex(true)); err != nil {
		errMsg := strings.ToLower(err.Error())
		if strings.Contains(errMsg, "already exists") || strings.Contains(errMsg, "permission denied") || strings.Contains(errMsg, "unexpected attribute change") || strings.Contains(errMsg, "expect identity") {
			log.Printf("Warning: Schema migration had issues: %v", err)
			log.Println("Continuing with existing schema...")
		} else {
			client.Close()
			return nil, err
		}
	} else {
		log.Println("Schema migration completed successfully")
	}

	if os.Getenv("MIGRATE_USERS_ROLE_ADMIN") == "true" {
		n, err := client.User.Update().SetRole(schema.UserRoleAdmin).Save(ctx)
		if err != nil {
			log.Printf("Warning: MIGRATE_USERS_ROLE_ADMIN failed: %v", err)
		} else {
			log.Printf("MIGRATE_USERS_ROLE_ADMIN: set role=admin on %d user(s)", n)
		}
	}

	return client, nil
}

func provideApp(
	client *ent.Client,
	usersRepository *repositories.UsersRepository,
	refreshTokensRepository *repositories.RefreshTokensRepository,
	memoryNodesRepository *repositories.MemoryNodesRepository,
	cardsRepository *repositories.CardsRepository,
	cardItemsRepository *repositories.CardItemsRepository,
	memoryNodesService *services.MemoryNodesService,
	cardsService *services.CardsService,
	cardItemsService *services.CardItemsService,
) *App {
	return &App{
		Client:                  client,
		UsersRepository:         usersRepository,
		RefreshTokensRepository: refreshTokensRepository,
		MemoryNodesRepository:   memoryNodesRepository,
		CardsRepository:         cardsRepository,
		CardItemsRepository:     cardItemsRepository,
		MemoryNodesService:      memoryNodesService,
		CardsService:            cardsService,
		CardItemsService:        cardItemsService,
		ctx:                     context.Background(),
	}
}
