// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CardsColumns holds the columns for the "cards" table.
	CardsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "question", Type: field.TypeJSON},
		{Name: "answer", Type: field.TypeJSON},
		{Name: "parent_nodes", Type: field.TypeJSON},
		{Name: "used", Type: field.TypeInt, Default: 0},
		{Name: "needed", Type: field.TypeInt, Default: 0},
		{Name: "count", Type: field.TypeInt, Default: 0},
		{Name: "reverse_count", Type: field.TypeInt, Default: 0},
		{Name: "usage_type", Type: field.TypeEnum, Enums: []string{"active", "passive", "transitional", "common"}, Default: "common"},
		{Name: "shared", Type: field.TypeBool, Default: false},
		{Name: "user_id", Type: field.TypeInt},
	}
	// CardsTable holds the schema information for the "cards" table.
	CardsTable = &schema.Table{
		Name:       "cards",
		Columns:    CardsColumns,
		PrimaryKey: []*schema.Column{CardsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "cards_users_cards",
				Columns:    []*schema.Column{CardsColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "card_usage_type",
				Unique:  false,
				Columns: []*schema.Column{CardsColumns[8]},
			},
			{
				Name:    "card_user_id",
				Unique:  false,
				Columns: []*schema.Column{CardsColumns[10]},
			},
			{
				Name:    "card_shared",
				Unique:  false,
				Columns: []*schema.Column{CardsColumns[9]},
			},
		},
	}
	// CardItemsColumns holds the columns for the "card_items" table.
	CardItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"TEXT", "TEXT_WITH_HIGHLIGHTED_SYMBOL", "CODE", "FORMULA", "IMAGE", "WORD_WITH_STRESS", "MARKDOWN"}},
		{Name: "text", Type: field.TypeString, Nullable: true},
		{Name: "index", Type: field.TypeInt, Nullable: true},
		{Name: "code", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "extension", Type: field.TypeString, Nullable: true},
		{Name: "formula", Type: field.TypeString, Nullable: true},
		{Name: "image_path", Type: field.TypeString, Nullable: true},
		{Name: "width", Type: field.TypeString, Nullable: true},
		{Name: "shared", Type: field.TypeBool, Default: false},
		{Name: "user_id", Type: field.TypeInt},
	}
	// CardItemsTable holds the schema information for the "card_items" table.
	CardItemsTable = &schema.Table{
		Name:       "card_items",
		Columns:    CardItemsColumns,
		PrimaryKey: []*schema.Column{CardItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "card_items_users_card_items",
				Columns:    []*schema.Column{CardItemsColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "carditem_type",
				Unique:  false,
				Columns: []*schema.Column{CardItemsColumns[1]},
			},
			{
				Name:    "carditem_user_id",
				Unique:  false,
				Columns: []*schema.Column{CardItemsColumns[10]},
			},
			{
				Name:    "carditem_shared",
				Unique:  false,
				Columns: []*schema.Column{CardItemsColumns[9]},
			},
		},
	}
	// CardUsersColumns holds the columns for the "card_users" table.
	CardUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "card_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// CardUsersTable holds the schema information for the "card_users" table.
	CardUsersTable = &schema.Table{
		Name:       "card_users",
		Columns:    CardUsersColumns,
		PrimaryKey: []*schema.Column{CardUsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "card_users_cards_card_users",
				Columns:    []*schema.Column{CardUsersColumns[1]},
				RefColumns: []*schema.Column{CardsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "card_users_users_card_users",
				Columns:    []*schema.Column{CardUsersColumns[2]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "carduser_card_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{CardUsersColumns[1], CardUsersColumns[2]},
			},
			{
				Name:    "carduser_user_id",
				Unique:  false,
				Columns: []*schema.Column{CardUsersColumns[2]},
			},
			{
				Name:    "carduser_card_id",
				Unique:  false,
				Columns: []*schema.Column{CardUsersColumns[1]},
			},
		},
	}
	// CardUserCountsColumns holds the columns for the "card_user_counts" table.
	CardUserCountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "count", Type: field.TypeInt, Default: 0},
		{Name: "card_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// CardUserCountsTable holds the schema information for the "card_user_counts" table.
	CardUserCountsTable = &schema.Table{
		Name:       "card_user_counts",
		Columns:    CardUserCountsColumns,
		PrimaryKey: []*schema.Column{CardUserCountsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "card_user_counts_cards_user_counts",
				Columns:    []*schema.Column{CardUserCountsColumns[2]},
				RefColumns: []*schema.Column{CardsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "card_user_counts_users_card_user_counts",
				Columns:    []*schema.Column{CardUserCountsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "cardusercount_card_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{CardUserCountsColumns[2], CardUserCountsColumns[3]},
			},
			{
				Name:    "cardusercount_user_id",
				Unique:  false,
				Columns: []*schema.Column{CardUserCountsColumns[3]},
			},
			{
				Name:    "cardusercount_card_id",
				Unique:  false,
				Columns: []*schema.Column{CardUserCountsColumns[2]},
			},
		},
	}
	// MemoryNodesColumns holds the columns for the "memory_nodes" table.
	MemoryNodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "children", Type: field.TypeJSON},
		{Name: "parents", Type: field.TypeJSON},
		{Name: "cards", Type: field.TypeJSON},
		{Name: "aliases", Type: field.TypeJSON},
		{Name: "priorities", Type: field.TypeJSON, Nullable: true},
		{Name: "groups", Type: field.TypeJSON, Nullable: true},
		{Name: "shared", Type: field.TypeBool, Default: false},
		{Name: "user_id", Type: field.TypeInt},
	}
	// MemoryNodesTable holds the schema information for the "memory_nodes" table.
	MemoryNodesTable = &schema.Table{
		Name:       "memory_nodes",
		Columns:    MemoryNodesColumns,
		PrimaryKey: []*schema.Column{MemoryNodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "memory_nodes_users_memory_nodes",
				Columns:    []*schema.Column{MemoryNodesColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "memorynode_user_id",
				Unique:  false,
				Columns: []*schema.Column{MemoryNodesColumns[10]},
			},
			{
				Name:    "memorynode_shared",
				Unique:  false,
				Columns: []*schema.Column{MemoryNodesColumns[9]},
			},
		},
	}
	// MemoryNodeUsersColumns holds the columns for the "memory_node_users" table.
	MemoryNodeUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "memory_node_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// MemoryNodeUsersTable holds the schema information for the "memory_node_users" table.
	MemoryNodeUsersTable = &schema.Table{
		Name:       "memory_node_users",
		Columns:    MemoryNodeUsersColumns,
		PrimaryKey: []*schema.Column{MemoryNodeUsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "memory_node_users_memory_nodes_memory_node_users",
				Columns:    []*schema.Column{MemoryNodeUsersColumns[1]},
				RefColumns: []*schema.Column{MemoryNodesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "memory_node_users_users_memory_node_users",
				Columns:    []*schema.Column{MemoryNodeUsersColumns[2]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "memorynodeuser_memory_node_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{MemoryNodeUsersColumns[1], MemoryNodeUsersColumns[2]},
			},
			{
				Name:    "memorynodeuser_user_id",
				Unique:  false,
				Columns: []*schema.Column{MemoryNodeUsersColumns[2]},
			},
			{
				Name:    "memorynodeuser_memory_node_id",
				Unique:  false,
				Columns: []*schema.Column{MemoryNodeUsersColumns[1]},
			},
		},
	}
	// RefreshTokensColumns holds the columns for the "refresh_tokens" table.
	RefreshTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
	}
	// RefreshTokensTable holds the schema information for the "refresh_tokens" table.
	RefreshTokensTable = &schema.Table{
		Name:       "refresh_tokens",
		Columns:    RefreshTokensColumns,
		PrimaryKey: []*schema.Column{RefreshTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "refresh_tokens_users_refresh_tokens",
				Columns:    []*schema.Column{RefreshTokensColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "login", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "user"}, Default: "user"},
		{Name: "verified", Type: field.TypeBool, Default: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// VerificationCodesColumns holds the columns for the "verification_codes" table.
	VerificationCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
	}
	// VerificationCodesTable holds the schema information for the "verification_codes" table.
	VerificationCodesTable = &schema.Table{
		Name:       "verification_codes",
		Columns:    VerificationCodesColumns,
		PrimaryKey: []*schema.Column{VerificationCodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "verification_codes_users_verification_codes",
				Columns:    []*schema.Column{VerificationCodesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CardsTable,
		CardItemsTable,
		CardUsersTable,
		CardUserCountsTable,
		MemoryNodesTable,
		MemoryNodeUsersTable,
		RefreshTokensTable,
		UsersTable,
		VerificationCodesTable,
	}
)

func init() {
	CardsTable.ForeignKeys[0].RefTable = UsersTable
	CardsTable.Annotation = &entsql.Annotation{
		Table: "cards",
	}
	CardItemsTable.ForeignKeys[0].RefTable = UsersTable
	CardItemsTable.Annotation = &entsql.Annotation{
		Table: "card_items",
	}
	CardUsersTable.ForeignKeys[0].RefTable = CardsTable
	CardUsersTable.ForeignKeys[1].RefTable = UsersTable
	CardUsersTable.Annotation = &entsql.Annotation{
		Table: "card_users",
	}
	CardUserCountsTable.ForeignKeys[0].RefTable = CardsTable
	CardUserCountsTable.ForeignKeys[1].RefTable = UsersTable
	CardUserCountsTable.Annotation = &entsql.Annotation{
		Table: "card_user_counts",
	}
	MemoryNodesTable.ForeignKeys[0].RefTable = UsersTable
	MemoryNodesTable.Annotation = &entsql.Annotation{
		Table: "memory_nodes",
	}
	MemoryNodeUsersTable.ForeignKeys[0].RefTable = MemoryNodesTable
	MemoryNodeUsersTable.ForeignKeys[1].RefTable = UsersTable
	MemoryNodeUsersTable.Annotation = &entsql.Annotation{
		Table: "memory_node_users",
	}
	RefreshTokensTable.ForeignKeys[0].RefTable = UsersTable
	RefreshTokensTable.Annotation = &entsql.Annotation{
		Table: "refresh_tokens",
	}
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
	VerificationCodesTable.ForeignKeys[0].RefTable = UsersTable
	VerificationCodesTable.Annotation = &entsql.Annotation{
		Table: "verification_codes",
	}
}
