// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/memoryguard/ent/carditem"
	"arturgudiev/memoryguard/ent/predicate"
	"arturgudiev/memoryguard/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CardItemUpdate is the builder for updating CardItem entities.
type CardItemUpdate struct {
	config
	hooks    []Hook
	mutation *CardItemMutation
}

// Where appends a list predicates to the CardItemUpdate builder.
func (_u *CardItemUpdate) Where(ps ...predicate.CardItem) *CardItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetText sets the "text" field.
func (_u *CardItemUpdate) SetText(v string) *CardItemUpdate {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *CardItemUpdate) SetNillableText(v *string) *CardItemUpdate {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// ClearText clears the value of the "text" field.
func (_u *CardItemUpdate) ClearText() *CardItemUpdate {
	_u.mutation.ClearText()
	return _u
}

// SetIndex sets the "index" field.
func (_u *CardItemUpdate) SetIndex(v int) *CardItemUpdate {
	_u.mutation.ResetIndex()
	_u.mutation.SetIndex(v)
	return _u
}

// SetNillableIndex sets the "index" field if the given value is not nil.
func (_u *CardItemUpdate) SetNillableIndex(v *int) *CardItemUpdate {
	if v != nil {
		_u.SetIndex(*v)
	}
	return _u
}

// AddIndex adds value to the "index" field.
func (_u *CardItemUpdate) AddIndex(v int) *CardItemUpdate {
	_u.mutation.AddIndex(v)
	return _u
}

// ClearIndex clears the value of the "index" field.
func (_u *CardItemUpdate) ClearIndex() *CardItemUpdate {
	_u.mutation.ClearIndex()
	return _u
}

// SetCode sets the "code" field.
func (_u *CardItemUpdate) SetCode(v string) *CardItemUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *CardItemUpdate) SetNillableCode(v *string) *CardItemUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// ClearCode clears the value of the "code" field.
func (_u *CardItemUpdate) ClearCode() *CardItemUpdate {
	_u.mutation.ClearCode()
	return _u
}

// SetExtension sets the "extension" field.
func (_u *CardItemUpdate) SetExtension(v string) *CardItemUpdate {
	_u.mutation.SetExtension(v)
	return _u
}

// SetNillableExtension sets the "extension" field if the given value is not nil.
func (_u *CardItemUpdate) SetNillableExtension(v *string) *CardItemUpdate {
	if v != nil {
		_u.SetExtension(*v)
	}
	return _u
}

// ClearExtension clears the value of the "extension" field.
func (_u *CardItemUpdate) ClearExtension() *CardItemUpdate {
	_u.mutation.ClearExtension()
	return _u
}

// SetFormula sets the "formula" field.
func (_u *CardItemUpdate) SetFormula(v string) *CardItemUpdate {
	_u.mutation.SetFormula(v)
	return _u
}

// SetNillableFormula sets the "formula" field if the given value is not nil.
func (_u *CardItemUpdate) SetNillableFormula(v *string) *CardItemUpdate {
	if v != nil {
		_u.SetFormula(*v)
	}
	return _u
}

// ClearFormula clears the value of the "formula" field.
func (_u *CardItemUpdate) ClearFormula() *CardItemUpdate {
	_u.mutation.ClearFormula()
	return _u
}

// SetImagePath sets the "image_path" field.
func (_u *CardItemUpdate) SetImagePath(v string) *CardItemUpdate {
	_u.mutation.SetImagePath(v)
	return _u
}

// SetNillableImagePath sets the "image_path" field if the given value is not nil.
func (_u *CardItemUpdate) SetNillableImagePath(v *string) *CardItemUpdate {
	if v != nil {
		_u.SetImagePath(*v)
	}
	return _u
}

// ClearImagePath clears the value of the "image_path" field.
func (_u *CardItemUpdate) ClearImagePath() *CardItemUpdate {
	_u.mutation.ClearImagePath()
	return _u
}

// SetWidth sets the "width" field.
func (_u *CardItemUpdate) SetWidth(v string) *CardItemUpdate {
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *CardItemUpdate) SetNillableWidth(v *string) *CardItemUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// ClearWidth clears the value of the "width" field.
func (_u *CardItemUpdate) ClearWidth() *CardItemUpdate {
	_u.mutation.ClearWidth()
	return _u
}

// SetShared sets the "shared" field.
func (_u *CardItemUpdate) SetShared(v bool) *CardItemUpdate {
	_u.mutation.SetShared(v)
	return _u
}

// SetNillableShared sets the "shared" field if the given value is not nil.
func (_u *CardItemUpdate) SetNillableShared(v *bool) *CardItemUpdate {
	if v != nil {
		_u.SetShared(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CardItemUpdate) SetUserID(v int) *CardItemUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CardItemUpdate) SetNillableUserID(v *int) *CardItemUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CardItemUpdate) SetUser(v *User) *CardItemUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CardItemMutation object of the builder.
func (_u *CardItemUpdate) Mutation() *CardItemMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CardItemUpdate) ClearUser() *CardItemUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CardItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CardItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CardItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CardItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CardItemUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := carditem.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "CardItem.user_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CardItem.user"`)
	}
	return nil
}

func (_u *CardItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(carditem.Table, carditem.Columns, sqlgraph.NewFieldSpec(carditem.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(carditem.FieldText, field.TypeString, value)
	}
	if _u.mutation.TextCleared() {
		_spec.ClearField(carditem.FieldText, field.TypeString)
	}
	if value, ok := _u.mutation.Index(); ok {
		_spec.SetField(carditem.FieldIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIndex(); ok {
		_spec.AddField(carditem.FieldIndex, field.TypeInt, value)
	}
	if _u.mutation.IndexCleared() {
		_spec.ClearField(carditem.FieldIndex, field.TypeInt)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(carditem.FieldCode, field.TypeString, value)
	}
	if _u.mutation.CodeCleared() {
		_spec.ClearField(carditem.FieldCode, field.TypeString)
	}
	if value, ok := _u.mutation.Extension(); ok {
		_spec.SetField(carditem.FieldExtension, field.TypeString, value)
	}
	if _u.mutation.ExtensionCleared() {
		_spec.ClearField(carditem.FieldExtension, field.TypeString)
	}
	if value, ok := _u.mutation.Formula(); ok {
		_spec.SetField(carditem.FieldFormula, field.TypeString, value)
	}
	if _u.mutation.FormulaCleared() {
		_spec.ClearField(carditem.FieldFormula, field.TypeString)
	}
	if value, ok := _u.mutation.ImagePath(); ok {
		_spec.SetField(carditem.FieldImagePath, field.TypeString, value)
	}
	if _u.mutation.ImagePathCleared() {
		_spec.ClearField(carditem.FieldImagePath, field.TypeString)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(carditem.FieldWidth, field.TypeString, value)
	}
	if _u.mutation.WidthCleared() {
		_spec.ClearField(carditem.FieldWidth, field.TypeString)
	}
	if value, ok := _u.mutation.Shared(); ok {
		_spec.SetField(carditem.FieldShared, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   carditem.UserTable,
			Columns: []string{carditem.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   carditem.UserTable,
			Columns: []string{carditem.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carditem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CardItemUpdateOne is the builder for updating a single CardItem entity.
type CardItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CardItemMutation
}

// SetText sets the "text" field.
func (_u *CardItemUpdateOne) SetText(v string) *CardItemUpdateOne {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *CardItemUpdateOne) SetNillableText(v *string) *CardItemUpdateOne {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// ClearText clears the value of the "text" field.
func (_u *CardItemUpdateOne) ClearText() *CardItemUpdateOne {
	_u.mutation.ClearText()
	return _u
}

// SetIndex sets the "index" field.
func (_u *CardItemUpdateOne) SetIndex(v int) *CardItemUpdateOne {
	_u.mutation.ResetIndex()
	_u.mutation.SetIndex(v)
	return _u
}

// SetNillableIndex sets the "index" field if the given value is not nil.
func (_u *CardItemUpdateOne) SetNillableIndex(v *int) *CardItemUpdateOne {
	if v != nil {
		_u.SetIndex(*v)
	}
	return _u
}

// AddIndex adds value to the "index" field.
func (_u *CardItemUpdateOne) AddIndex(v int) *CardItemUpdateOne {
	_u.mutation.AddIndex(v)
	return _u
}

// ClearIndex clears the value of the "index" field.
func (_u *CardItemUpdateOne) ClearIndex() *CardItemUpdateOne {
	_u.mutation.ClearIndex()
	return _u
}

// SetCode sets the "code" field.
func (_u *CardItemUpdateOne) SetCode(v string) *CardItemUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *CardItemUpdateOne) SetNillableCode(v *string) *CardItemUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// ClearCode clears the value of the "code" field.
func (_u *CardItemUpdateOne) ClearCode() *CardItemUpdateOne {
	_u.mutation.ClearCode()
	return _u
}

// SetExtension sets the "extension" field.
func (_u *CardItemUpdateOne) SetExtension(v string) *CardItemUpdateOne {
	_u.mutation.SetExtension(v)
	return _u
}

// SetNillableExtension sets the "extension" field if the given value is not nil.
func (_u *CardItemUpdateOne) SetNillableExtension(v *string) *CardItemUpdateOne {
	if v != nil {
		_u.SetExtension(*v)
	}
	return _u
}

// ClearExtension clears the value of the "extension" field.
func (_u *CardItemUpdateOne) ClearExtension() *CardItemUpdateOne {
	_u.mutation.ClearExtension()
	return _u
}

// SetFormula sets the "formula" field.
func (_u *CardItemUpdateOne) SetFormula(v string) *CardItemUpdateOne {
	_u.mutation.SetFormula(v)
	return _u
}

// SetNillableFormula sets the "formula" field if the given value is not nil.
func (_u *CardItemUpdateOne) SetNillableFormula(v *string) *CardItemUpdateOne {
	if v != nil {
		_u.SetFormula(*v)
	}
	return _u
}

// ClearFormula clears the value of the "formula" field.
func (_u *CardItemUpdateOne) ClearFormula() *CardItemUpdateOne {
	_u.mutation.ClearFormula()
	return _u
}

// SetImagePath sets the "image_path" field.
func (_u *CardItemUpdateOne) SetImagePath(v string) *CardItemUpdateOne {
	_u.mutation.SetImagePath(v)
	return _u
}

// SetNillableImagePath sets the "image_path" field if the given value is not nil.
func (_u *CardItemUpdateOne) SetNillableImagePath(v *string) *CardItemUpdateOne {
	if v != nil {
		_u.SetImagePath(*v)
	}
	return _u
}

// ClearImagePath clears the value of the "image_path" field.
func (_u *CardItemUpdateOne) ClearImagePath() *CardItemUpdateOne {
	_u.mutation.ClearImagePath()
	return _u
}

// SetWidth sets the "width" field.
func (_u *CardItemUpdateOne) SetWidth(v string) *CardItemUpdateOne {
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *CardItemUpdateOne) SetNillableWidth(v *string) *CardItemUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// ClearWidth clears the value of the "width" field.
func (_u *CardItemUpdateOne) ClearWidth() *CardItemUpdateOne {
	_u.mutation.ClearWidth()
	return _u
}

// SetShared sets the "shared" field.
func (_u *CardItemUpdateOne) SetShared(v bool) *CardItemUpdateOne {
	_u.mutation.SetShared(v)
	return _u
}

// SetNillableShared sets the "shared" field if the given value is not nil.
func (_u *CardItemUpdateOne) SetNillableShared(v *bool) *CardItemUpdateOne {
	if v != nil {
		_u.SetShared(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CardItemUpdateOne) SetUserID(v int) *CardItemUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CardItemUpdateOne) SetNillableUserID(v *int) *CardItemUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CardItemUpdateOne) SetUser(v *User) *CardItemUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CardItemMutation object of the builder.
func (_u *CardItemUpdateOne) Mutation() *CardItemMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CardItemUpdateOne) ClearUser() *CardItemUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the CardItemUpdate builder.
func (_u *CardItemUpdateOne) Where(ps ...predicate.CardItem) *CardItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CardItemUpdateOne) Select(field string, fields ...string) *CardItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CardItem entity.
func (_u *CardItemUpdateOne) Save(ctx context.Context) (*CardItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CardItemUpdateOne) SaveX(ctx context.Context) *CardItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CardItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CardItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CardItemUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := carditem.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "CardItem.user_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CardItem.user"`)
	}
	return nil
}

func (_u *CardItemUpdateOne) sqlSave(ctx context.Context) (_node *CardItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(carditem.Table, carditem.Columns, sqlgraph.NewFieldSpec(carditem.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CardItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, carditem.FieldID)
		for _, f := range fields {
			if !carditem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != carditem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(carditem.FieldText, field.TypeString, value)
	}
	if _u.mutation.TextCleared() {
		_spec.ClearField(carditem.FieldText, field.TypeString)
	}
	if value, ok := _u.mutation.Index(); ok {
		_spec.SetField(carditem.FieldIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIndex(); ok {
		_spec.AddField(carditem.FieldIndex, field.TypeInt, value)
	}
	if _u.mutation.IndexCleared() {
		_spec.ClearField(carditem.FieldIndex, field.TypeInt)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(carditem.FieldCode, field.TypeString, value)
	}
	if _u.mutation.CodeCleared() {
		_spec.ClearField(carditem.FieldCode, field.TypeString)
	}
	if value, ok := _u.mutation.Extension(); ok {
		_spec.SetField(carditem.FieldExtension, field.TypeString, value)
	}
	if _u.mutation.ExtensionCleared() {
		_spec.ClearField(carditem.FieldExtension, field.TypeString)
	}
	if value, ok := _u.mutation.Formula(); ok {
		_spec.SetField(carditem.FieldFormula, field.TypeString, value)
	}
	if _u.mutation.FormulaCleared() {
		_spec.ClearField(carditem.FieldFormula, field.TypeString)
	}
	if value, ok := _u.mutation.ImagePath(); ok {
		_spec.SetField(carditem.FieldImagePath, field.TypeString, value)
	}
	if _u.mutation.ImagePathCleared() {
		_spec.ClearField(carditem.FieldImagePath, field.TypeString)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(carditem.FieldWidth, field.TypeString, value)
	}
	if _u.mutation.WidthCleared() {
		_spec.ClearField(carditem.FieldWidth, field.TypeString)
	}
	if value, ok := _u.mutation.Shared(); ok {
		_spec.SetField(carditem.FieldShared, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   carditem.UserTable,
			Columns: []string{carditem.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   carditem.UserTable,
			Columns: []string{carditem.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CardItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carditem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
