// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/memoryguard/ent/card"
	"arturgudiev/memoryguard/ent/cardusercount"
	"arturgudiev/memoryguard/ent/user"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CardUserCount is the model entity for the CardUserCount schema.
type CardUserCount struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CardID holds the value of the "card_id" field.
	CardID int `json:"card_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Count holds the value of the "count" field.
	Count int `json:"count,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CardUserCountQuery when eager-loading is set.
	Edges        CardUserCountEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CardUserCountEdges holds the relations/edges for other nodes in the graph.
type CardUserCountEdges struct {
	// Card holds the value of the card edge.
	Card *Card `json:"card,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CardOrErr returns the Card value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CardUserCountEdges) CardOrErr() (*Card, error) {
	if e.Card != nil {
		return e.Card, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: card.Label}
	}
	return nil, &NotLoadedError{edge: "card"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CardUserCountEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CardUserCount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cardusercount.FieldID, cardusercount.FieldCardID, cardusercount.FieldUserID, cardusercount.FieldCount:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CardUserCount fields.
func (_m *CardUserCount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cardusercount.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case cardusercount.FieldCardID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field card_id", values[i])
			} else if value.Valid {
				_m.CardID = int(value.Int64)
			}
		case cardusercount.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case cardusercount.FieldCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field count", values[i])
			} else if value.Valid {
				_m.Count = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CardUserCount.
// This includes values selected through modifiers, order, etc.
func (_m *CardUserCount) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCard queries the "card" edge of the CardUserCount entity.
func (_m *CardUserCount) QueryCard() *CardQuery {
	return NewCardUserCountClient(_m.config).QueryCard(_m)
}

// QueryUser queries the "user" edge of the CardUserCount entity.
func (_m *CardUserCount) QueryUser() *UserQuery {
	return NewCardUserCountClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this CardUserCount.
// Note that you need to call CardUserCount.Unwrap() before calling this method if this CardUserCount
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CardUserCount) Update() *CardUserCountUpdateOne {
	return NewCardUserCountClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CardUserCount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CardUserCount) Unwrap() *CardUserCount {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CardUserCount is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CardUserCount) String() string {
	var builder strings.Builder
	builder.WriteString("CardUserCount(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("card_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CardID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("count=")
	builder.WriteString(fmt.Sprintf("%v", _m.Count))
	builder.WriteByte(')')
	return builder.String()
}

// CardUserCounts is a parsable slice of CardUserCount.
type CardUserCounts []*CardUserCount
