// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/memoryguard/ent/card"
	"arturgudiev/memoryguard/ent/cardusercount"
	"arturgudiev/memoryguard/ent/predicate"
	"arturgudiev/memoryguard/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CardUserCountUpdate is the builder for updating CardUserCount entities.
type CardUserCountUpdate struct {
	config
	hooks    []Hook
	mutation *CardUserCountMutation
}

// Where appends a list predicates to the CardUserCountUpdate builder.
func (_u *CardUserCountUpdate) Where(ps ...predicate.CardUserCount) *CardUserCountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCardID sets the "card_id" field.
func (_u *CardUserCountUpdate) SetCardID(v int) *CardUserCountUpdate {
	_u.mutation.SetCardID(v)
	return _u
}

// SetNillableCardID sets the "card_id" field if the given value is not nil.
func (_u *CardUserCountUpdate) SetNillableCardID(v *int) *CardUserCountUpdate {
	if v != nil {
		_u.SetCardID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CardUserCountUpdate) SetUserID(v int) *CardUserCountUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CardUserCountUpdate) SetNillableUserID(v *int) *CardUserCountUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCount sets the "count" field.
func (_u *CardUserCountUpdate) SetCount(v int) *CardUserCountUpdate {
	_u.mutation.ResetCount()
	_u.mutation.SetCount(v)
	return _u
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_u *CardUserCountUpdate) SetNillableCount(v *int) *CardUserCountUpdate {
	if v != nil {
		_u.SetCount(*v)
	}
	return _u
}

// AddCount adds value to the "count" field.
func (_u *CardUserCountUpdate) AddCount(v int) *CardUserCountUpdate {
	_u.mutation.AddCount(v)
	return _u
}

// SetCard sets the "card" edge to the Card entity.
func (_u *CardUserCountUpdate) SetCard(v *Card) *CardUserCountUpdate {
	return _u.SetCardID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *CardUserCountUpdate) SetUser(v *User) *CardUserCountUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CardUserCountMutation object of the builder.
func (_u *CardUserCountUpdate) Mutation() *CardUserCountMutation {
	return _u.mutation
}

// ClearCard clears the "card" edge to the Card entity.
func (_u *CardUserCountUpdate) ClearCard() *CardUserCountUpdate {
	_u.mutation.ClearCard()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CardUserCountUpdate) ClearUser() *CardUserCountUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CardUserCountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CardUserCountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CardUserCountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CardUserCountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CardUserCountUpdate) check() error {
	if v, ok := _u.mutation.CardID(); ok {
		if err := cardusercount.CardIDValidator(v); err != nil {
			return &ValidationError{Name: "card_id", err: fmt.Errorf(`ent: validator failed for field "CardUserCount.card_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := cardusercount.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "CardUserCount.user_id": %w`, err)}
		}
	}
	if _u.mutation.CardCleared() && len(_u.mutation.CardIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CardUserCount.card"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CardUserCount.user"`)
	}
	return nil
}

func (_u *CardUserCountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cardusercount.Table, cardusercount.Columns, sqlgraph.NewFieldSpec(cardusercount.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Count(); ok {
		_spec.SetField(cardusercount.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.AddField(cardusercount.FieldCount, field.TypeInt, value)
	}
	if _u.mutation.CardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cardusercount.CardTable,
			Columns: []string{cardusercount.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cardusercount.CardTable,
			Columns: []string{cardusercount.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cardusercount.UserTable,
			Columns: []string{cardusercount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cardusercount.UserTable,
			Columns: []string{cardusercount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cardusercount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CardUserCountUpdateOne is the builder for updating a single CardUserCount entity.
type CardUserCountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CardUserCountMutation
}

// SetCardID sets the "card_id" field.
func (_u *CardUserCountUpdateOne) SetCardID(v int) *CardUserCountUpdateOne {
	_u.mutation.SetCardID(v)
	return _u
}

// SetNillableCardID sets the "card_id" field if the given value is not nil.
func (_u *CardUserCountUpdateOne) SetNillableCardID(v *int) *CardUserCountUpdateOne {
	if v != nil {
		_u.SetCardID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CardUserCountUpdateOne) SetUserID(v int) *CardUserCountUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CardUserCountUpdateOne) SetNillableUserID(v *int) *CardUserCountUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCount sets the "count" field.
func (_u *CardUserCountUpdateOne) SetCount(v int) *CardUserCountUpdateOne {
	_u.mutation.ResetCount()
	_u.mutation.SetCount(v)
	return _u
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_u *CardUserCountUpdateOne) SetNillableCount(v *int) *CardUserCountUpdateOne {
	if v != nil {
		_u.SetCount(*v)
	}
	return _u
}

// AddCount adds value to the "count" field.
func (_u *CardUserCountUpdateOne) AddCount(v int) *CardUserCountUpdateOne {
	_u.mutation.AddCount(v)
	return _u
}

// SetCard sets the "card" edge to the Card entity.
func (_u *CardUserCountUpdateOne) SetCard(v *Card) *CardUserCountUpdateOne {
	return _u.SetCardID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *CardUserCountUpdateOne) SetUser(v *User) *CardUserCountUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CardUserCountMutation object of the builder.
func (_u *CardUserCountUpdateOne) Mutation() *CardUserCountMutation {
	return _u.mutation
}

// ClearCard clears the "card" edge to the Card entity.
func (_u *CardUserCountUpdateOne) ClearCard() *CardUserCountUpdateOne {
	_u.mutation.ClearCard()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CardUserCountUpdateOne) ClearUser() *CardUserCountUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the CardUserCountUpdate builder.
func (_u *CardUserCountUpdateOne) Where(ps ...predicate.CardUserCount) *CardUserCountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CardUserCountUpdateOne) Select(field string, fields ...string) *CardUserCountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CardUserCount entity.
func (_u *CardUserCountUpdateOne) Save(ctx context.Context) (*CardUserCount, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CardUserCountUpdateOne) SaveX(ctx context.Context) *CardUserCount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CardUserCountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CardUserCountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CardUserCountUpdateOne) check() error {
	if v, ok := _u.mutation.CardID(); ok {
		if err := cardusercount.CardIDValidator(v); err != nil {
			return &ValidationError{Name: "card_id", err: fmt.Errorf(`ent: validator failed for field "CardUserCount.card_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := cardusercount.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "CardUserCount.user_id": %w`, err)}
		}
	}
	if _u.mutation.CardCleared() && len(_u.mutation.CardIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CardUserCount.card"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CardUserCount.user"`)
	}
	return nil
}

func (_u *CardUserCountUpdateOne) sqlSave(ctx context.Context) (_node *CardUserCount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cardusercount.Table, cardusercount.Columns, sqlgraph.NewFieldSpec(cardusercount.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CardUserCount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cardusercount.FieldID)
		for _, f := range fields {
			if !cardusercount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cardusercount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Count(); ok {
		_spec.SetField(cardusercount.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.AddField(cardusercount.FieldCount, field.TypeInt, value)
	}
	if _u.mutation.CardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cardusercount.CardTable,
			Columns: []string{cardusercount.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cardusercount.CardTable,
			Columns: []string{cardusercount.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cardusercount.UserTable,
			Columns: []string{cardusercount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cardusercount.UserTable,
			Columns: []string{cardusercount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CardUserCount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cardusercount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
