// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/memoryguard/ent/card"
	"arturgudiev/memoryguard/ent/schema"
	"arturgudiev/memoryguard/ent/user"
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Card is the model entity for the Card schema.
type Card struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Question holds the value of the "question" field.
	Question []int `json:"question,omitempty"`
	// Answer holds the value of the "answer" field.
	Answer []int `json:"answer,omitempty"`
	// ParentNodes holds the value of the "parent_nodes" field.
	ParentNodes []int `json:"parent_nodes,omitempty"`
	// Used holds the value of the "used" field.
	Used int `json:"used,omitempty"`
	// Needed holds the value of the "needed" field.
	Needed int `json:"needed,omitempty"`
	// Count holds the value of the "count" field.
	Count int `json:"count,omitempty"`
	// ReverseCount holds the value of the "reverse_count" field.
	ReverseCount int `json:"reverse_count,omitempty"`
	// PracticeCount holds the value of the "practice_count" field.
	PracticeCount int `json:"practice_count,omitempty"`
	// UsageType holds the value of the "usage_type" field.
	UsageType schema.UsageType `json:"usage_type,omitempty"`
	// Shared holds the value of the "shared" field.
	Shared bool `json:"shared,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CardQuery when eager-loading is set.
	Edges        CardEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CardEdges holds the relations/edges for other nodes in the graph.
type CardEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CardEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Card) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case card.FieldQuestion, card.FieldAnswer, card.FieldParentNodes:
			values[i] = new([]byte)
		case card.FieldShared:
			values[i] = new(sql.NullBool)
		case card.FieldID, card.FieldUsed, card.FieldNeeded, card.FieldCount, card.FieldReverseCount, card.FieldPracticeCount, card.FieldUserID:
			values[i] = new(sql.NullInt64)
		case card.FieldUsageType:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Card fields.
func (_m *Card) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case card.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case card.FieldQuestion:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field question", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Question); err != nil {
					return fmt.Errorf("unmarshal field question: %w", err)
				}
			}
		case card.FieldAnswer:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field answer", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Answer); err != nil {
					return fmt.Errorf("unmarshal field answer: %w", err)
				}
			}
		case card.FieldParentNodes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field parent_nodes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ParentNodes); err != nil {
					return fmt.Errorf("unmarshal field parent_nodes: %w", err)
				}
			}
		case card.FieldUsed:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field used", values[i])
			} else if value.Valid {
				_m.Used = int(value.Int64)
			}
		case card.FieldNeeded:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field needed", values[i])
			} else if value.Valid {
				_m.Needed = int(value.Int64)
			}
		case card.FieldCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field count", values[i])
			} else if value.Valid {
				_m.Count = int(value.Int64)
			}
		case card.FieldReverseCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reverse_count", values[i])
			} else if value.Valid {
				_m.ReverseCount = int(value.Int64)
			}
		case card.FieldPracticeCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field practice_count", values[i])
			} else if value.Valid {
				_m.PracticeCount = int(value.Int64)
			}
		case card.FieldUsageType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field usage_type", values[i])
			} else if value.Valid {
				_m.UsageType = schema.UsageType(value.String)
			}
		case card.FieldShared:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field shared", values[i])
			} else if value.Valid {
				_m.Shared = value.Bool
			}
		case card.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Card.
// This includes values selected through modifiers, order, etc.
func (_m *Card) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Card entity.
func (_m *Card) QueryUser() *UserQuery {
	return NewCardClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this Card.
// Note that you need to call Card.Unwrap() before calling this method if this Card
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Card) Update() *CardUpdateOne {
	return NewCardClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Card entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Card) Unwrap() *Card {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Card is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Card) String() string {
	var builder strings.Builder
	builder.WriteString("Card(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("question=")
	builder.WriteString(fmt.Sprintf("%v", _m.Question))
	builder.WriteString(", ")
	builder.WriteString("answer=")
	builder.WriteString(fmt.Sprintf("%v", _m.Answer))
	builder.WriteString(", ")
	builder.WriteString("parent_nodes=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentNodes))
	builder.WriteString(", ")
	builder.WriteString("used=")
	builder.WriteString(fmt.Sprintf("%v", _m.Used))
	builder.WriteString(", ")
	builder.WriteString("needed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Needed))
	builder.WriteString(", ")
	builder.WriteString("count=")
	builder.WriteString(fmt.Sprintf("%v", _m.Count))
	builder.WriteString(", ")
	builder.WriteString("reverse_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReverseCount))
	builder.WriteString(", ")
	builder.WriteString("practice_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.PracticeCount))
	builder.WriteString(", ")
	builder.WriteString("usage_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsageType))
	builder.WriteString(", ")
	builder.WriteString("shared=")
	builder.WriteString(fmt.Sprintf("%v", _m.Shared))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteByte(')')
	return builder.String()
}

// Cards is a parsable slice of Card.
type Cards []*Card
