// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/memoryguard/ent/card"
	"arturgudiev/memoryguard/ent/schema"
	"arturgudiev/memoryguard/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CardCreate is the builder for creating a Card entity.
type CardCreate struct {
	config
	mutation *CardMutation
	hooks    []Hook
}

// SetQuestion sets the "question" field.
func (_c *CardCreate) SetQuestion(v []int) *CardCreate {
	_c.mutation.SetQuestion(v)
	return _c
}

// SetAnswer sets the "answer" field.
func (_c *CardCreate) SetAnswer(v []int) *CardCreate {
	_c.mutation.SetAnswer(v)
	return _c
}

// SetParentNodes sets the "parent_nodes" field.
func (_c *CardCreate) SetParentNodes(v []int) *CardCreate {
	_c.mutation.SetParentNodes(v)
	return _c
}

// SetUsed sets the "used" field.
func (_c *CardCreate) SetUsed(v int) *CardCreate {
	_c.mutation.SetUsed(v)
	return _c
}

// SetNillableUsed sets the "used" field if the given value is not nil.
func (_c *CardCreate) SetNillableUsed(v *int) *CardCreate {
	if v != nil {
		_c.SetUsed(*v)
	}
	return _c
}

// SetNeeded sets the "needed" field.
func (_c *CardCreate) SetNeeded(v int) *CardCreate {
	_c.mutation.SetNeeded(v)
	return _c
}

// SetNillableNeeded sets the "needed" field if the given value is not nil.
func (_c *CardCreate) SetNillableNeeded(v *int) *CardCreate {
	if v != nil {
		_c.SetNeeded(*v)
	}
	return _c
}

// SetCount sets the "count" field.
func (_c *CardCreate) SetCount(v int) *CardCreate {
	_c.mutation.SetCount(v)
	return _c
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_c *CardCreate) SetNillableCount(v *int) *CardCreate {
	if v != nil {
		_c.SetCount(*v)
	}
	return _c
}

// SetReverseCount sets the "reverse_count" field.
func (_c *CardCreate) SetReverseCount(v int) *CardCreate {
	_c.mutation.SetReverseCount(v)
	return _c
}

// SetNillableReverseCount sets the "reverse_count" field if the given value is not nil.
func (_c *CardCreate) SetNillableReverseCount(v *int) *CardCreate {
	if v != nil {
		_c.SetReverseCount(*v)
	}
	return _c
}

// SetUsageType sets the "usage_type" field.
func (_c *CardCreate) SetUsageType(v schema.UsageType) *CardCreate {
	_c.mutation.SetUsageType(v)
	return _c
}

// SetNillableUsageType sets the "usage_type" field if the given value is not nil.
func (_c *CardCreate) SetNillableUsageType(v *schema.UsageType) *CardCreate {
	if v != nil {
		_c.SetUsageType(*v)
	}
	return _c
}

// SetShared sets the "shared" field.
func (_c *CardCreate) SetShared(v bool) *CardCreate {
	_c.mutation.SetShared(v)
	return _c
}

// SetNillableShared sets the "shared" field if the given value is not nil.
func (_c *CardCreate) SetNillableShared(v *bool) *CardCreate {
	if v != nil {
		_c.SetShared(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CardCreate) SetUserID(v int) *CardCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *CardCreate) SetID(v int) *CardCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CardCreate) SetUser(v *User) *CardCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the CardMutation object of the builder.
func (_c *CardCreate) Mutation() *CardMutation {
	return _c.mutation
}

// Save creates the Card in the database.
func (_c *CardCreate) Save(ctx context.Context) (*Card, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CardCreate) SaveX(ctx context.Context) *Card {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CardCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CardCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CardCreate) defaults() {
	if _, ok := _c.mutation.Question(); !ok {
		v := card.DefaultQuestion
		_c.mutation.SetQuestion(v)
	}
	if _, ok := _c.mutation.Answer(); !ok {
		v := card.DefaultAnswer
		_c.mutation.SetAnswer(v)
	}
	if _, ok := _c.mutation.ParentNodes(); !ok {
		v := card.DefaultParentNodes
		_c.mutation.SetParentNodes(v)
	}
	if _, ok := _c.mutation.Used(); !ok {
		v := card.DefaultUsed
		_c.mutation.SetUsed(v)
	}
	if _, ok := _c.mutation.Needed(); !ok {
		v := card.DefaultNeeded
		_c.mutation.SetNeeded(v)
	}
	if _, ok := _c.mutation.Count(); !ok {
		v := card.DefaultCount
		_c.mutation.SetCount(v)
	}
	if _, ok := _c.mutation.ReverseCount(); !ok {
		v := card.DefaultReverseCount
		_c.mutation.SetReverseCount(v)
	}
	if _, ok := _c.mutation.UsageType(); !ok {
		v := card.DefaultUsageType
		_c.mutation.SetUsageType(v)
	}
	if _, ok := _c.mutation.Shared(); !ok {
		v := card.DefaultShared
		_c.mutation.SetShared(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CardCreate) check() error {
	if _, ok := _c.mutation.Question(); !ok {
		return &ValidationError{Name: "question", err: errors.New(`ent: missing required field "Card.question"`)}
	}
	if _, ok := _c.mutation.Answer(); !ok {
		return &ValidationError{Name: "answer", err: errors.New(`ent: missing required field "Card.answer"`)}
	}
	if _, ok := _c.mutation.ParentNodes(); !ok {
		return &ValidationError{Name: "parent_nodes", err: errors.New(`ent: missing required field "Card.parent_nodes"`)}
	}
	if _, ok := _c.mutation.Used(); !ok {
		return &ValidationError{Name: "used", err: errors.New(`ent: missing required field "Card.used"`)}
	}
	if _, ok := _c.mutation.Needed(); !ok {
		return &ValidationError{Name: "needed", err: errors.New(`ent: missing required field "Card.needed"`)}
	}
	if _, ok := _c.mutation.Count(); !ok {
		return &ValidationError{Name: "count", err: errors.New(`ent: missing required field "Card.count"`)}
	}
	if _, ok := _c.mutation.ReverseCount(); !ok {
		return &ValidationError{Name: "reverse_count", err: errors.New(`ent: missing required field "Card.reverse_count"`)}
	}
	if _, ok := _c.mutation.UsageType(); !ok {
		return &ValidationError{Name: "usage_type", err: errors.New(`ent: missing required field "Card.usage_type"`)}
	}
	if v, ok := _c.mutation.UsageType(); ok {
		if err := card.UsageTypeValidator(v); err != nil {
			return &ValidationError{Name: "usage_type", err: fmt.Errorf(`ent: validator failed for field "Card.usage_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Shared(); !ok {
		return &ValidationError{Name: "shared", err: errors.New(`ent: missing required field "Card.shared"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Card.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := card.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Card.user_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := card.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Card.id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Card.user"`)}
	}
	return nil
}

func (_c *CardCreate) sqlSave(ctx context.Context) (*Card, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CardCreate) createSpec() (*Card, *sqlgraph.CreateSpec) {
	var (
		_node = &Card{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(card.Table, sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Question(); ok {
		_spec.SetField(card.FieldQuestion, field.TypeJSON, value)
		_node.Question = value
	}
	if value, ok := _c.mutation.Answer(); ok {
		_spec.SetField(card.FieldAnswer, field.TypeJSON, value)
		_node.Answer = value
	}
	if value, ok := _c.mutation.ParentNodes(); ok {
		_spec.SetField(card.FieldParentNodes, field.TypeJSON, value)
		_node.ParentNodes = value
	}
	if value, ok := _c.mutation.Used(); ok {
		_spec.SetField(card.FieldUsed, field.TypeInt, value)
		_node.Used = value
	}
	if value, ok := _c.mutation.Needed(); ok {
		_spec.SetField(card.FieldNeeded, field.TypeInt, value)
		_node.Needed = value
	}
	if value, ok := _c.mutation.Count(); ok {
		_spec.SetField(card.FieldCount, field.TypeInt, value)
		_node.Count = value
	}
	if value, ok := _c.mutation.ReverseCount(); ok {
		_spec.SetField(card.FieldReverseCount, field.TypeInt, value)
		_node.ReverseCount = value
	}
	if value, ok := _c.mutation.UsageType(); ok {
		_spec.SetField(card.FieldUsageType, field.TypeEnum, value)
		_node.UsageType = value
	}
	if value, ok := _c.mutation.Shared(); ok {
		_spec.SetField(card.FieldShared, field.TypeBool, value)
		_node.Shared = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.UserTable,
			Columns: []string{card.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CardCreateBulk is the builder for creating many Card entities in bulk.
type CardCreateBulk struct {
	config
	err      error
	builders []*CardCreate
}

// Save creates the Card entities in the database.
func (_c *CardCreateBulk) Save(ctx context.Context) ([]*Card, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Card, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CardCreateBulk) SaveX(ctx context.Context) []*Card {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CardCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CardCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
