// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/memoryguard/ent/carditem"
	"arturgudiev/memoryguard/ent/schema"
	"arturgudiev/memoryguard/ent/user"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CardItem is the model entity for the CardItem schema.
type CardItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type schema.CardItemType `json:"type,omitempty"`
	// Text holds the value of the "text" field.
	Text *string `json:"text,omitempty"`
	// Index holds the value of the "index" field.
	Index *int `json:"index,omitempty"`
	// Code holds the value of the "code" field.
	Code *string `json:"code,omitempty"`
	// Extension holds the value of the "extension" field.
	Extension *string `json:"extension,omitempty"`
	// Formula holds the value of the "formula" field.
	Formula *string `json:"formula,omitempty"`
	// ImagePath holds the value of the "image_path" field.
	ImagePath *string `json:"image_path,omitempty"`
	// Width holds the value of the "width" field.
	Width *string `json:"width,omitempty"`
	// Shared holds the value of the "shared" field.
	Shared bool `json:"shared,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CardItemQuery when eager-loading is set.
	Edges        CardItemEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CardItemEdges holds the relations/edges for other nodes in the graph.
type CardItemEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CardItemEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CardItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case carditem.FieldShared:
			values[i] = new(sql.NullBool)
		case carditem.FieldID, carditem.FieldIndex, carditem.FieldUserID:
			values[i] = new(sql.NullInt64)
		case carditem.FieldType, carditem.FieldText, carditem.FieldCode, carditem.FieldExtension, carditem.FieldFormula, carditem.FieldImagePath, carditem.FieldWidth:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CardItem fields.
func (_m *CardItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case carditem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case carditem.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = schema.CardItemType(value.String)
			}
		case carditem.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				_m.Text = new(string)
				*_m.Text = value.String
			}
		case carditem.FieldIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field index", values[i])
			} else if value.Valid {
				_m.Index = new(int)
				*_m.Index = int(value.Int64)
			}
		case carditem.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = new(string)
				*_m.Code = value.String
			}
		case carditem.FieldExtension:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field extension", values[i])
			} else if value.Valid {
				_m.Extension = new(string)
				*_m.Extension = value.String
			}
		case carditem.FieldFormula:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field formula", values[i])
			} else if value.Valid {
				_m.Formula = new(string)
				*_m.Formula = value.String
			}
		case carditem.FieldImagePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_path", values[i])
			} else if value.Valid {
				_m.ImagePath = new(string)
				*_m.ImagePath = value.String
			}
		case carditem.FieldWidth:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field width", values[i])
			} else if value.Valid {
				_m.Width = new(string)
				*_m.Width = value.String
			}
		case carditem.FieldShared:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field shared", values[i])
			} else if value.Valid {
				_m.Shared = value.Bool
			}
		case carditem.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CardItem.
// This includes values selected through modifiers, order, etc.
func (_m *CardItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the CardItem entity.
func (_m *CardItem) QueryUser() *UserQuery {
	return NewCardItemClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this CardItem.
// Note that you need to call CardItem.Unwrap() before calling this method if this CardItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CardItem) Update() *CardItemUpdateOne {
	return NewCardItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CardItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CardItem) Unwrap() *CardItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CardItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CardItem) String() string {
	var builder strings.Builder
	builder.WriteString("CardItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	if v := _m.Text; v != nil {
		builder.WriteString("text=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Index; v != nil {
		builder.WriteString("index=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Code; v != nil {
		builder.WriteString("code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Extension; v != nil {
		builder.WriteString("extension=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Formula; v != nil {
		builder.WriteString("formula=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ImagePath; v != nil {
		builder.WriteString("image_path=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Width; v != nil {
		builder.WriteString("width=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("shared=")
	builder.WriteString(fmt.Sprintf("%v", _m.Shared))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteByte(')')
	return builder.String()
}

// CardItems is a parsable slice of CardItem.
type CardItems []*CardItem
