// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/memoryguard/ent/card"
	"arturgudiev/memoryguard/ent/carduser"
	"arturgudiev/memoryguard/ent/predicate"
	"arturgudiev/memoryguard/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CardUserUpdate is the builder for updating CardUser entities.
type CardUserUpdate struct {
	config
	hooks    []Hook
	mutation *CardUserMutation
}

// Where appends a list predicates to the CardUserUpdate builder.
func (_u *CardUserUpdate) Where(ps ...predicate.CardUser) *CardUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCardID sets the "card_id" field.
func (_u *CardUserUpdate) SetCardID(v int) *CardUserUpdate {
	_u.mutation.SetCardID(v)
	return _u
}

// SetNillableCardID sets the "card_id" field if the given value is not nil.
func (_u *CardUserUpdate) SetNillableCardID(v *int) *CardUserUpdate {
	if v != nil {
		_u.SetCardID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CardUserUpdate) SetUserID(v int) *CardUserUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CardUserUpdate) SetNillableUserID(v *int) *CardUserUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCard sets the "card" edge to the Card entity.
func (_u *CardUserUpdate) SetCard(v *Card) *CardUserUpdate {
	return _u.SetCardID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *CardUserUpdate) SetUser(v *User) *CardUserUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CardUserMutation object of the builder.
func (_u *CardUserUpdate) Mutation() *CardUserMutation {
	return _u.mutation
}

// ClearCard clears the "card" edge to the Card entity.
func (_u *CardUserUpdate) ClearCard() *CardUserUpdate {
	_u.mutation.ClearCard()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CardUserUpdate) ClearUser() *CardUserUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CardUserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CardUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CardUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CardUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CardUserUpdate) check() error {
	if v, ok := _u.mutation.CardID(); ok {
		if err := carduser.CardIDValidator(v); err != nil {
			return &ValidationError{Name: "card_id", err: fmt.Errorf(`ent: validator failed for field "CardUser.card_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := carduser.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "CardUser.user_id": %w`, err)}
		}
	}
	if _u.mutation.CardCleared() && len(_u.mutation.CardIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CardUser.card"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CardUser.user"`)
	}
	return nil
}

func (_u *CardUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(carduser.Table, carduser.Columns, sqlgraph.NewFieldSpec(carduser.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   carduser.CardTable,
			Columns: []string{carduser.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   carduser.CardTable,
			Columns: []string{carduser.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   carduser.UserTable,
			Columns: []string{carduser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   carduser.UserTable,
			Columns: []string{carduser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carduser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CardUserUpdateOne is the builder for updating a single CardUser entity.
type CardUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CardUserMutation
}

// SetCardID sets the "card_id" field.
func (_u *CardUserUpdateOne) SetCardID(v int) *CardUserUpdateOne {
	_u.mutation.SetCardID(v)
	return _u
}

// SetNillableCardID sets the "card_id" field if the given value is not nil.
func (_u *CardUserUpdateOne) SetNillableCardID(v *int) *CardUserUpdateOne {
	if v != nil {
		_u.SetCardID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CardUserUpdateOne) SetUserID(v int) *CardUserUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CardUserUpdateOne) SetNillableUserID(v *int) *CardUserUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCard sets the "card" edge to the Card entity.
func (_u *CardUserUpdateOne) SetCard(v *Card) *CardUserUpdateOne {
	return _u.SetCardID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *CardUserUpdateOne) SetUser(v *User) *CardUserUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CardUserMutation object of the builder.
func (_u *CardUserUpdateOne) Mutation() *CardUserMutation {
	return _u.mutation
}

// ClearCard clears the "card" edge to the Card entity.
func (_u *CardUserUpdateOne) ClearCard() *CardUserUpdateOne {
	_u.mutation.ClearCard()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CardUserUpdateOne) ClearUser() *CardUserUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the CardUserUpdate builder.
func (_u *CardUserUpdateOne) Where(ps ...predicate.CardUser) *CardUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CardUserUpdateOne) Select(field string, fields ...string) *CardUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CardUser entity.
func (_u *CardUserUpdateOne) Save(ctx context.Context) (*CardUser, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CardUserUpdateOne) SaveX(ctx context.Context) *CardUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CardUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CardUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CardUserUpdateOne) check() error {
	if v, ok := _u.mutation.CardID(); ok {
		if err := carduser.CardIDValidator(v); err != nil {
			return &ValidationError{Name: "card_id", err: fmt.Errorf(`ent: validator failed for field "CardUser.card_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := carduser.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "CardUser.user_id": %w`, err)}
		}
	}
	if _u.mutation.CardCleared() && len(_u.mutation.CardIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CardUser.card"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CardUser.user"`)
	}
	return nil
}

func (_u *CardUserUpdateOne) sqlSave(ctx context.Context) (_node *CardUser, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(carduser.Table, carduser.Columns, sqlgraph.NewFieldSpec(carduser.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CardUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, carduser.FieldID)
		for _, f := range fields {
			if !carduser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != carduser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   carduser.CardTable,
			Columns: []string{carduser.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   carduser.CardTable,
			Columns: []string{carduser.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   carduser.UserTable,
			Columns: []string{carduser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   carduser.UserTable,
			Columns: []string{carduser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CardUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carduser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
