// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/memoryguard/ent/card"
	"arturgudiev/memoryguard/ent/carduser"
	"arturgudiev/memoryguard/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CardUserCreate is the builder for creating a CardUser entity.
type CardUserCreate struct {
	config
	mutation *CardUserMutation
	hooks    []Hook
}

// SetCardID sets the "card_id" field.
func (_c *CardUserCreate) SetCardID(v int) *CardUserCreate {
	_c.mutation.SetCardID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CardUserCreate) SetUserID(v int) *CardUserCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *CardUserCreate) SetID(v int) *CardUserCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetCard sets the "card" edge to the Card entity.
func (_c *CardUserCreate) SetCard(v *Card) *CardUserCreate {
	return _c.SetCardID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *CardUserCreate) SetUser(v *User) *CardUserCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the CardUserMutation object of the builder.
func (_c *CardUserCreate) Mutation() *CardUserMutation {
	return _c.mutation
}

// Save creates the CardUser in the database.
func (_c *CardUserCreate) Save(ctx context.Context) (*CardUser, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CardUserCreate) SaveX(ctx context.Context) *CardUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CardUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CardUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CardUserCreate) check() error {
	if _, ok := _c.mutation.CardID(); !ok {
		return &ValidationError{Name: "card_id", err: errors.New(`ent: missing required field "CardUser.card_id"`)}
	}
	if v, ok := _c.mutation.CardID(); ok {
		if err := carduser.CardIDValidator(v); err != nil {
			return &ValidationError{Name: "card_id", err: fmt.Errorf(`ent: validator failed for field "CardUser.card_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CardUser.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := carduser.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "CardUser.user_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := carduser.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "CardUser.id": %w`, err)}
		}
	}
	if len(_c.mutation.CardIDs()) == 0 {
		return &ValidationError{Name: "card", err: errors.New(`ent: missing required edge "CardUser.card"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CardUser.user"`)}
	}
	return nil
}

func (_c *CardUserCreate) sqlSave(ctx context.Context) (*CardUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CardUserCreate) createSpec() (*CardUser, *sqlgraph.CreateSpec) {
	var (
		_node = &CardUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(carduser.Table, sqlgraph.NewFieldSpec(carduser.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if nodes := _c.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   carduser.CardTable,
			Columns: []string{carduser.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CardID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   carduser.UserTable,
			Columns: []string{carduser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CardUserCreateBulk is the builder for creating many CardUser entities in bulk.
type CardUserCreateBulk struct {
	config
	err      error
	builders []*CardUserCreate
}

// Save creates the CardUser entities in the database.
func (_c *CardUserCreateBulk) Save(ctx context.Context) ([]*CardUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CardUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CardUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CardUserCreateBulk) SaveX(ctx context.Context) []*CardUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CardUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CardUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
