// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"arturgudiev/memoryguard/ent/migrate"

	"arturgudiev/memoryguard/ent/card"
	"arturgudiev/memoryguard/ent/carditem"
	"arturgudiev/memoryguard/ent/carduser"
	"arturgudiev/memoryguard/ent/cardusercount"
	"arturgudiev/memoryguard/ent/memorynode"
	"arturgudiev/memoryguard/ent/memorynodeuser"
	"arturgudiev/memoryguard/ent/refreshtoken"
	"arturgudiev/memoryguard/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Card is the client for interacting with the Card builders.
	Card *CardClient
	// CardItem is the client for interacting with the CardItem builders.
	CardItem *CardItemClient
	// CardUser is the client for interacting with the CardUser builders.
	CardUser *CardUserClient
	// CardUserCount is the client for interacting with the CardUserCount builders.
	CardUserCount *CardUserCountClient
	// MemoryNode is the client for interacting with the MemoryNode builders.
	MemoryNode *MemoryNodeClient
	// MemoryNodeUser is the client for interacting with the MemoryNodeUser builders.
	MemoryNodeUser *MemoryNodeUserClient
	// RefreshToken is the client for interacting with the RefreshToken builders.
	RefreshToken *RefreshTokenClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Card = NewCardClient(c.config)
	c.CardItem = NewCardItemClient(c.config)
	c.CardUser = NewCardUserClient(c.config)
	c.CardUserCount = NewCardUserCountClient(c.config)
	c.MemoryNode = NewMemoryNodeClient(c.config)
	c.MemoryNodeUser = NewMemoryNodeUserClient(c.config)
	c.RefreshToken = NewRefreshTokenClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		Card:           NewCardClient(cfg),
		CardItem:       NewCardItemClient(cfg),
		CardUser:       NewCardUserClient(cfg),
		CardUserCount:  NewCardUserCountClient(cfg),
		MemoryNode:     NewMemoryNodeClient(cfg),
		MemoryNodeUser: NewMemoryNodeUserClient(cfg),
		RefreshToken:   NewRefreshTokenClient(cfg),
		User:           NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		Card:           NewCardClient(cfg),
		CardItem:       NewCardItemClient(cfg),
		CardUser:       NewCardUserClient(cfg),
		CardUserCount:  NewCardUserCountClient(cfg),
		MemoryNode:     NewMemoryNodeClient(cfg),
		MemoryNodeUser: NewMemoryNodeUserClient(cfg),
		RefreshToken:   NewRefreshTokenClient(cfg),
		User:           NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Card.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Card, c.CardItem, c.CardUser, c.CardUserCount, c.MemoryNode, c.MemoryNodeUser,
		c.RefreshToken, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Card, c.CardItem, c.CardUser, c.CardUserCount, c.MemoryNode, c.MemoryNodeUser,
		c.RefreshToken, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CardMutation:
		return c.Card.mutate(ctx, m)
	case *CardItemMutation:
		return c.CardItem.mutate(ctx, m)
	case *CardUserMutation:
		return c.CardUser.mutate(ctx, m)
	case *CardUserCountMutation:
		return c.CardUserCount.mutate(ctx, m)
	case *MemoryNodeMutation:
		return c.MemoryNode.mutate(ctx, m)
	case *MemoryNodeUserMutation:
		return c.MemoryNodeUser.mutate(ctx, m)
	case *RefreshTokenMutation:
		return c.RefreshToken.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CardClient is a client for the Card schema.
type CardClient struct {
	config
}

// NewCardClient returns a client for the Card from the given config.
func NewCardClient(c config) *CardClient {
	return &CardClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `card.Hooks(f(g(h())))`.
func (c *CardClient) Use(hooks ...Hook) {
	c.hooks.Card = append(c.hooks.Card, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `card.Intercept(f(g(h())))`.
func (c *CardClient) Intercept(interceptors ...Interceptor) {
	c.inters.Card = append(c.inters.Card, interceptors...)
}

// Create returns a builder for creating a Card entity.
func (c *CardClient) Create() *CardCreate {
	mutation := newCardMutation(c.config, OpCreate)
	return &CardCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Card entities.
func (c *CardClient) CreateBulk(builders ...*CardCreate) *CardCreateBulk {
	return &CardCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CardClient) MapCreateBulk(slice any, setFunc func(*CardCreate, int)) *CardCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CardCreateBulk{err: fmt.Errorf("calling to CardClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CardCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CardCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Card.
func (c *CardClient) Update() *CardUpdate {
	mutation := newCardMutation(c.config, OpUpdate)
	return &CardUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CardClient) UpdateOne(_m *Card) *CardUpdateOne {
	mutation := newCardMutation(c.config, OpUpdateOne, withCard(_m))
	return &CardUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CardClient) UpdateOneID(id int) *CardUpdateOne {
	mutation := newCardMutation(c.config, OpUpdateOne, withCardID(id))
	return &CardUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Card.
func (c *CardClient) Delete() *CardDelete {
	mutation := newCardMutation(c.config, OpDelete)
	return &CardDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CardClient) DeleteOne(_m *Card) *CardDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CardClient) DeleteOneID(id int) *CardDeleteOne {
	builder := c.Delete().Where(card.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CardDeleteOne{builder}
}

// Query returns a query builder for Card.
func (c *CardClient) Query() *CardQuery {
	return &CardQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCard},
		inters: c.Interceptors(),
	}
}

// Get returns a Card entity by its id.
func (c *CardClient) Get(ctx context.Context, id int) (*Card, error) {
	return c.Query().Where(card.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CardClient) GetX(ctx context.Context, id int) *Card {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a Card.
func (c *CardClient) QueryUser(_m *Card) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(card.Table, card.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, card.UserTable, card.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUserCounts queries the user_counts edge of a Card.
func (c *CardClient) QueryUserCounts(_m *Card) *CardUserCountQuery {
	query := (&CardUserCountClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(card.Table, card.FieldID, id),
			sqlgraph.To(cardusercount.Table, cardusercount.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, card.UserCountsTable, card.UserCountsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCardUsers queries the card_users edge of a Card.
func (c *CardClient) QueryCardUsers(_m *Card) *CardUserQuery {
	query := (&CardUserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(card.Table, card.FieldID, id),
			sqlgraph.To(carduser.Table, carduser.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, card.CardUsersTable, card.CardUsersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CardClient) Hooks() []Hook {
	return c.hooks.Card
}

// Interceptors returns the client interceptors.
func (c *CardClient) Interceptors() []Interceptor {
	return c.inters.Card
}

func (c *CardClient) mutate(ctx context.Context, m *CardMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CardCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CardUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CardUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CardDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Card mutation op: %q", m.Op())
	}
}

// CardItemClient is a client for the CardItem schema.
type CardItemClient struct {
	config
}

// NewCardItemClient returns a client for the CardItem from the given config.
func NewCardItemClient(c config) *CardItemClient {
	return &CardItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `carditem.Hooks(f(g(h())))`.
func (c *CardItemClient) Use(hooks ...Hook) {
	c.hooks.CardItem = append(c.hooks.CardItem, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `carditem.Intercept(f(g(h())))`.
func (c *CardItemClient) Intercept(interceptors ...Interceptor) {
	c.inters.CardItem = append(c.inters.CardItem, interceptors...)
}

// Create returns a builder for creating a CardItem entity.
func (c *CardItemClient) Create() *CardItemCreate {
	mutation := newCardItemMutation(c.config, OpCreate)
	return &CardItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CardItem entities.
func (c *CardItemClient) CreateBulk(builders ...*CardItemCreate) *CardItemCreateBulk {
	return &CardItemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CardItemClient) MapCreateBulk(slice any, setFunc func(*CardItemCreate, int)) *CardItemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CardItemCreateBulk{err: fmt.Errorf("calling to CardItemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CardItemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CardItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CardItem.
func (c *CardItemClient) Update() *CardItemUpdate {
	mutation := newCardItemMutation(c.config, OpUpdate)
	return &CardItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CardItemClient) UpdateOne(_m *CardItem) *CardItemUpdateOne {
	mutation := newCardItemMutation(c.config, OpUpdateOne, withCardItem(_m))
	return &CardItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CardItemClient) UpdateOneID(id int) *CardItemUpdateOne {
	mutation := newCardItemMutation(c.config, OpUpdateOne, withCardItemID(id))
	return &CardItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CardItem.
func (c *CardItemClient) Delete() *CardItemDelete {
	mutation := newCardItemMutation(c.config, OpDelete)
	return &CardItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CardItemClient) DeleteOne(_m *CardItem) *CardItemDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CardItemClient) DeleteOneID(id int) *CardItemDeleteOne {
	builder := c.Delete().Where(carditem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CardItemDeleteOne{builder}
}

// Query returns a query builder for CardItem.
func (c *CardItemClient) Query() *CardItemQuery {
	return &CardItemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCardItem},
		inters: c.Interceptors(),
	}
}

// Get returns a CardItem entity by its id.
func (c *CardItemClient) Get(ctx context.Context, id int) (*CardItem, error) {
	return c.Query().Where(carditem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CardItemClient) GetX(ctx context.Context, id int) *CardItem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a CardItem.
func (c *CardItemClient) QueryUser(_m *CardItem) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(carditem.Table, carditem.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, carditem.UserTable, carditem.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CardItemClient) Hooks() []Hook {
	return c.hooks.CardItem
}

// Interceptors returns the client interceptors.
func (c *CardItemClient) Interceptors() []Interceptor {
	return c.inters.CardItem
}

func (c *CardItemClient) mutate(ctx context.Context, m *CardItemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CardItemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CardItemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CardItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CardItemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CardItem mutation op: %q", m.Op())
	}
}

// CardUserClient is a client for the CardUser schema.
type CardUserClient struct {
	config
}

// NewCardUserClient returns a client for the CardUser from the given config.
func NewCardUserClient(c config) *CardUserClient {
	return &CardUserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `carduser.Hooks(f(g(h())))`.
func (c *CardUserClient) Use(hooks ...Hook) {
	c.hooks.CardUser = append(c.hooks.CardUser, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `carduser.Intercept(f(g(h())))`.
func (c *CardUserClient) Intercept(interceptors ...Interceptor) {
	c.inters.CardUser = append(c.inters.CardUser, interceptors...)
}

// Create returns a builder for creating a CardUser entity.
func (c *CardUserClient) Create() *CardUserCreate {
	mutation := newCardUserMutation(c.config, OpCreate)
	return &CardUserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CardUser entities.
func (c *CardUserClient) CreateBulk(builders ...*CardUserCreate) *CardUserCreateBulk {
	return &CardUserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CardUserClient) MapCreateBulk(slice any, setFunc func(*CardUserCreate, int)) *CardUserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CardUserCreateBulk{err: fmt.Errorf("calling to CardUserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CardUserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CardUserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CardUser.
func (c *CardUserClient) Update() *CardUserUpdate {
	mutation := newCardUserMutation(c.config, OpUpdate)
	return &CardUserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CardUserClient) UpdateOne(_m *CardUser) *CardUserUpdateOne {
	mutation := newCardUserMutation(c.config, OpUpdateOne, withCardUser(_m))
	return &CardUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CardUserClient) UpdateOneID(id int) *CardUserUpdateOne {
	mutation := newCardUserMutation(c.config, OpUpdateOne, withCardUserID(id))
	return &CardUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CardUser.
func (c *CardUserClient) Delete() *CardUserDelete {
	mutation := newCardUserMutation(c.config, OpDelete)
	return &CardUserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CardUserClient) DeleteOne(_m *CardUser) *CardUserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CardUserClient) DeleteOneID(id int) *CardUserDeleteOne {
	builder := c.Delete().Where(carduser.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CardUserDeleteOne{builder}
}

// Query returns a query builder for CardUser.
func (c *CardUserClient) Query() *CardUserQuery {
	return &CardUserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCardUser},
		inters: c.Interceptors(),
	}
}

// Get returns a CardUser entity by its id.
func (c *CardUserClient) Get(ctx context.Context, id int) (*CardUser, error) {
	return c.Query().Where(carduser.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CardUserClient) GetX(ctx context.Context, id int) *CardUser {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCard queries the card edge of a CardUser.
func (c *CardUserClient) QueryCard(_m *CardUser) *CardQuery {
	query := (&CardClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(carduser.Table, carduser.FieldID, id),
			sqlgraph.To(card.Table, card.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, carduser.CardTable, carduser.CardColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUser queries the user edge of a CardUser.
func (c *CardUserClient) QueryUser(_m *CardUser) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(carduser.Table, carduser.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, carduser.UserTable, carduser.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CardUserClient) Hooks() []Hook {
	return c.hooks.CardUser
}

// Interceptors returns the client interceptors.
func (c *CardUserClient) Interceptors() []Interceptor {
	return c.inters.CardUser
}

func (c *CardUserClient) mutate(ctx context.Context, m *CardUserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CardUserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CardUserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CardUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CardUserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CardUser mutation op: %q", m.Op())
	}
}

// CardUserCountClient is a client for the CardUserCount schema.
type CardUserCountClient struct {
	config
}

// NewCardUserCountClient returns a client for the CardUserCount from the given config.
func NewCardUserCountClient(c config) *CardUserCountClient {
	return &CardUserCountClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `cardusercount.Hooks(f(g(h())))`.
func (c *CardUserCountClient) Use(hooks ...Hook) {
	c.hooks.CardUserCount = append(c.hooks.CardUserCount, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `cardusercount.Intercept(f(g(h())))`.
func (c *CardUserCountClient) Intercept(interceptors ...Interceptor) {
	c.inters.CardUserCount = append(c.inters.CardUserCount, interceptors...)
}

// Create returns a builder for creating a CardUserCount entity.
func (c *CardUserCountClient) Create() *CardUserCountCreate {
	mutation := newCardUserCountMutation(c.config, OpCreate)
	return &CardUserCountCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CardUserCount entities.
func (c *CardUserCountClient) CreateBulk(builders ...*CardUserCountCreate) *CardUserCountCreateBulk {
	return &CardUserCountCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CardUserCountClient) MapCreateBulk(slice any, setFunc func(*CardUserCountCreate, int)) *CardUserCountCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CardUserCountCreateBulk{err: fmt.Errorf("calling to CardUserCountClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CardUserCountCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CardUserCountCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CardUserCount.
func (c *CardUserCountClient) Update() *CardUserCountUpdate {
	mutation := newCardUserCountMutation(c.config, OpUpdate)
	return &CardUserCountUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CardUserCountClient) UpdateOne(_m *CardUserCount) *CardUserCountUpdateOne {
	mutation := newCardUserCountMutation(c.config, OpUpdateOne, withCardUserCount(_m))
	return &CardUserCountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CardUserCountClient) UpdateOneID(id int) *CardUserCountUpdateOne {
	mutation := newCardUserCountMutation(c.config, OpUpdateOne, withCardUserCountID(id))
	return &CardUserCountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CardUserCount.
func (c *CardUserCountClient) Delete() *CardUserCountDelete {
	mutation := newCardUserCountMutation(c.config, OpDelete)
	return &CardUserCountDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CardUserCountClient) DeleteOne(_m *CardUserCount) *CardUserCountDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CardUserCountClient) DeleteOneID(id int) *CardUserCountDeleteOne {
	builder := c.Delete().Where(cardusercount.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CardUserCountDeleteOne{builder}
}

// Query returns a query builder for CardUserCount.
func (c *CardUserCountClient) Query() *CardUserCountQuery {
	return &CardUserCountQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCardUserCount},
		inters: c.Interceptors(),
	}
}

// Get returns a CardUserCount entity by its id.
func (c *CardUserCountClient) Get(ctx context.Context, id int) (*CardUserCount, error) {
	return c.Query().Where(cardusercount.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CardUserCountClient) GetX(ctx context.Context, id int) *CardUserCount {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCard queries the card edge of a CardUserCount.
func (c *CardUserCountClient) QueryCard(_m *CardUserCount) *CardQuery {
	query := (&CardClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(cardusercount.Table, cardusercount.FieldID, id),
			sqlgraph.To(card.Table, card.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, cardusercount.CardTable, cardusercount.CardColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUser queries the user edge of a CardUserCount.
func (c *CardUserCountClient) QueryUser(_m *CardUserCount) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(cardusercount.Table, cardusercount.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, cardusercount.UserTable, cardusercount.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CardUserCountClient) Hooks() []Hook {
	return c.hooks.CardUserCount
}

// Interceptors returns the client interceptors.
func (c *CardUserCountClient) Interceptors() []Interceptor {
	return c.inters.CardUserCount
}

func (c *CardUserCountClient) mutate(ctx context.Context, m *CardUserCountMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CardUserCountCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CardUserCountUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CardUserCountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CardUserCountDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CardUserCount mutation op: %q", m.Op())
	}
}

// MemoryNodeClient is a client for the MemoryNode schema.
type MemoryNodeClient struct {
	config
}

// NewMemoryNodeClient returns a client for the MemoryNode from the given config.
func NewMemoryNodeClient(c config) *MemoryNodeClient {
	return &MemoryNodeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `memorynode.Hooks(f(g(h())))`.
func (c *MemoryNodeClient) Use(hooks ...Hook) {
	c.hooks.MemoryNode = append(c.hooks.MemoryNode, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `memorynode.Intercept(f(g(h())))`.
func (c *MemoryNodeClient) Intercept(interceptors ...Interceptor) {
	c.inters.MemoryNode = append(c.inters.MemoryNode, interceptors...)
}

// Create returns a builder for creating a MemoryNode entity.
func (c *MemoryNodeClient) Create() *MemoryNodeCreate {
	mutation := newMemoryNodeMutation(c.config, OpCreate)
	return &MemoryNodeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MemoryNode entities.
func (c *MemoryNodeClient) CreateBulk(builders ...*MemoryNodeCreate) *MemoryNodeCreateBulk {
	return &MemoryNodeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MemoryNodeClient) MapCreateBulk(slice any, setFunc func(*MemoryNodeCreate, int)) *MemoryNodeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MemoryNodeCreateBulk{err: fmt.Errorf("calling to MemoryNodeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MemoryNodeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MemoryNodeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MemoryNode.
func (c *MemoryNodeClient) Update() *MemoryNodeUpdate {
	mutation := newMemoryNodeMutation(c.config, OpUpdate)
	return &MemoryNodeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MemoryNodeClient) UpdateOne(_m *MemoryNode) *MemoryNodeUpdateOne {
	mutation := newMemoryNodeMutation(c.config, OpUpdateOne, withMemoryNode(_m))
	return &MemoryNodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MemoryNodeClient) UpdateOneID(id int) *MemoryNodeUpdateOne {
	mutation := newMemoryNodeMutation(c.config, OpUpdateOne, withMemoryNodeID(id))
	return &MemoryNodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MemoryNode.
func (c *MemoryNodeClient) Delete() *MemoryNodeDelete {
	mutation := newMemoryNodeMutation(c.config, OpDelete)
	return &MemoryNodeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MemoryNodeClient) DeleteOne(_m *MemoryNode) *MemoryNodeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MemoryNodeClient) DeleteOneID(id int) *MemoryNodeDeleteOne {
	builder := c.Delete().Where(memorynode.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MemoryNodeDeleteOne{builder}
}

// Query returns a query builder for MemoryNode.
func (c *MemoryNodeClient) Query() *MemoryNodeQuery {
	return &MemoryNodeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMemoryNode},
		inters: c.Interceptors(),
	}
}

// Get returns a MemoryNode entity by its id.
func (c *MemoryNodeClient) Get(ctx context.Context, id int) (*MemoryNode, error) {
	return c.Query().Where(memorynode.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MemoryNodeClient) GetX(ctx context.Context, id int) *MemoryNode {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a MemoryNode.
func (c *MemoryNodeClient) QueryUser(_m *MemoryNode) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(memorynode.Table, memorynode.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, memorynode.UserTable, memorynode.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMemoryNodeUsers queries the memory_node_users edge of a MemoryNode.
func (c *MemoryNodeClient) QueryMemoryNodeUsers(_m *MemoryNode) *MemoryNodeUserQuery {
	query := (&MemoryNodeUserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(memorynode.Table, memorynode.FieldID, id),
			sqlgraph.To(memorynodeuser.Table, memorynodeuser.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, memorynode.MemoryNodeUsersTable, memorynode.MemoryNodeUsersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MemoryNodeClient) Hooks() []Hook {
	return c.hooks.MemoryNode
}

// Interceptors returns the client interceptors.
func (c *MemoryNodeClient) Interceptors() []Interceptor {
	return c.inters.MemoryNode
}

func (c *MemoryNodeClient) mutate(ctx context.Context, m *MemoryNodeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MemoryNodeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MemoryNodeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MemoryNodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MemoryNodeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MemoryNode mutation op: %q", m.Op())
	}
}

// MemoryNodeUserClient is a client for the MemoryNodeUser schema.
type MemoryNodeUserClient struct {
	config
}

// NewMemoryNodeUserClient returns a client for the MemoryNodeUser from the given config.
func NewMemoryNodeUserClient(c config) *MemoryNodeUserClient {
	return &MemoryNodeUserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `memorynodeuser.Hooks(f(g(h())))`.
func (c *MemoryNodeUserClient) Use(hooks ...Hook) {
	c.hooks.MemoryNodeUser = append(c.hooks.MemoryNodeUser, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `memorynodeuser.Intercept(f(g(h())))`.
func (c *MemoryNodeUserClient) Intercept(interceptors ...Interceptor) {
	c.inters.MemoryNodeUser = append(c.inters.MemoryNodeUser, interceptors...)
}

// Create returns a builder for creating a MemoryNodeUser entity.
func (c *MemoryNodeUserClient) Create() *MemoryNodeUserCreate {
	mutation := newMemoryNodeUserMutation(c.config, OpCreate)
	return &MemoryNodeUserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MemoryNodeUser entities.
func (c *MemoryNodeUserClient) CreateBulk(builders ...*MemoryNodeUserCreate) *MemoryNodeUserCreateBulk {
	return &MemoryNodeUserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MemoryNodeUserClient) MapCreateBulk(slice any, setFunc func(*MemoryNodeUserCreate, int)) *MemoryNodeUserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MemoryNodeUserCreateBulk{err: fmt.Errorf("calling to MemoryNodeUserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MemoryNodeUserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MemoryNodeUserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MemoryNodeUser.
func (c *MemoryNodeUserClient) Update() *MemoryNodeUserUpdate {
	mutation := newMemoryNodeUserMutation(c.config, OpUpdate)
	return &MemoryNodeUserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MemoryNodeUserClient) UpdateOne(_m *MemoryNodeUser) *MemoryNodeUserUpdateOne {
	mutation := newMemoryNodeUserMutation(c.config, OpUpdateOne, withMemoryNodeUser(_m))
	return &MemoryNodeUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MemoryNodeUserClient) UpdateOneID(id int) *MemoryNodeUserUpdateOne {
	mutation := newMemoryNodeUserMutation(c.config, OpUpdateOne, withMemoryNodeUserID(id))
	return &MemoryNodeUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MemoryNodeUser.
func (c *MemoryNodeUserClient) Delete() *MemoryNodeUserDelete {
	mutation := newMemoryNodeUserMutation(c.config, OpDelete)
	return &MemoryNodeUserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MemoryNodeUserClient) DeleteOne(_m *MemoryNodeUser) *MemoryNodeUserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MemoryNodeUserClient) DeleteOneID(id int) *MemoryNodeUserDeleteOne {
	builder := c.Delete().Where(memorynodeuser.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MemoryNodeUserDeleteOne{builder}
}

// Query returns a query builder for MemoryNodeUser.
func (c *MemoryNodeUserClient) Query() *MemoryNodeUserQuery {
	return &MemoryNodeUserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMemoryNodeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a MemoryNodeUser entity by its id.
func (c *MemoryNodeUserClient) Get(ctx context.Context, id int) (*MemoryNodeUser, error) {
	return c.Query().Where(memorynodeuser.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MemoryNodeUserClient) GetX(ctx context.Context, id int) *MemoryNodeUser {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMemoryNode queries the memory_node edge of a MemoryNodeUser.
func (c *MemoryNodeUserClient) QueryMemoryNode(_m *MemoryNodeUser) *MemoryNodeQuery {
	query := (&MemoryNodeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(memorynodeuser.Table, memorynodeuser.FieldID, id),
			sqlgraph.To(memorynode.Table, memorynode.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, memorynodeuser.MemoryNodeTable, memorynodeuser.MemoryNodeColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUser queries the user edge of a MemoryNodeUser.
func (c *MemoryNodeUserClient) QueryUser(_m *MemoryNodeUser) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(memorynodeuser.Table, memorynodeuser.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, memorynodeuser.UserTable, memorynodeuser.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MemoryNodeUserClient) Hooks() []Hook {
	return c.hooks.MemoryNodeUser
}

// Interceptors returns the client interceptors.
func (c *MemoryNodeUserClient) Interceptors() []Interceptor {
	return c.inters.MemoryNodeUser
}

func (c *MemoryNodeUserClient) mutate(ctx context.Context, m *MemoryNodeUserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MemoryNodeUserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MemoryNodeUserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MemoryNodeUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MemoryNodeUserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MemoryNodeUser mutation op: %q", m.Op())
	}
}

// RefreshTokenClient is a client for the RefreshToken schema.
type RefreshTokenClient struct {
	config
}

// NewRefreshTokenClient returns a client for the RefreshToken from the given config.
func NewRefreshTokenClient(c config) *RefreshTokenClient {
	return &RefreshTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `refreshtoken.Hooks(f(g(h())))`.
func (c *RefreshTokenClient) Use(hooks ...Hook) {
	c.hooks.RefreshToken = append(c.hooks.RefreshToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `refreshtoken.Intercept(f(g(h())))`.
func (c *RefreshTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.RefreshToken = append(c.inters.RefreshToken, interceptors...)
}

// Create returns a builder for creating a RefreshToken entity.
func (c *RefreshTokenClient) Create() *RefreshTokenCreate {
	mutation := newRefreshTokenMutation(c.config, OpCreate)
	return &RefreshTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RefreshToken entities.
func (c *RefreshTokenClient) CreateBulk(builders ...*RefreshTokenCreate) *RefreshTokenCreateBulk {
	return &RefreshTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RefreshTokenClient) MapCreateBulk(slice any, setFunc func(*RefreshTokenCreate, int)) *RefreshTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RefreshTokenCreateBulk{err: fmt.Errorf("calling to RefreshTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RefreshTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RefreshTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RefreshToken.
func (c *RefreshTokenClient) Update() *RefreshTokenUpdate {
	mutation := newRefreshTokenMutation(c.config, OpUpdate)
	return &RefreshTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RefreshTokenClient) UpdateOne(_m *RefreshToken) *RefreshTokenUpdateOne {
	mutation := newRefreshTokenMutation(c.config, OpUpdateOne, withRefreshToken(_m))
	return &RefreshTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RefreshTokenClient) UpdateOneID(id string) *RefreshTokenUpdateOne {
	mutation := newRefreshTokenMutation(c.config, OpUpdateOne, withRefreshTokenID(id))
	return &RefreshTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RefreshToken.
func (c *RefreshTokenClient) Delete() *RefreshTokenDelete {
	mutation := newRefreshTokenMutation(c.config, OpDelete)
	return &RefreshTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RefreshTokenClient) DeleteOne(_m *RefreshToken) *RefreshTokenDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RefreshTokenClient) DeleteOneID(id string) *RefreshTokenDeleteOne {
	builder := c.Delete().Where(refreshtoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RefreshTokenDeleteOne{builder}
}

// Query returns a query builder for RefreshToken.
func (c *RefreshTokenClient) Query() *RefreshTokenQuery {
	return &RefreshTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRefreshToken},
		inters: c.Interceptors(),
	}
}

// Get returns a RefreshToken entity by its id.
func (c *RefreshTokenClient) Get(ctx context.Context, id string) (*RefreshToken, error) {
	return c.Query().Where(refreshtoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RefreshTokenClient) GetX(ctx context.Context, id string) *RefreshToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a RefreshToken.
func (c *RefreshTokenClient) QueryUser(_m *RefreshToken) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(refreshtoken.Table, refreshtoken.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, refreshtoken.UserTable, refreshtoken.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RefreshTokenClient) Hooks() []Hook {
	return c.hooks.RefreshToken
}

// Interceptors returns the client interceptors.
func (c *RefreshTokenClient) Interceptors() []Interceptor {
	return c.inters.RefreshToken
}

func (c *RefreshTokenClient) mutate(ctx context.Context, m *RefreshTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RefreshTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RefreshTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RefreshTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RefreshTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RefreshToken mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRefreshTokens queries the refresh_tokens edge of a User.
func (c *UserClient) QueryRefreshTokens(_m *User) *RefreshTokenQuery {
	query := (&RefreshTokenClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(refreshtoken.Table, refreshtoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.RefreshTokensTable, user.RefreshTokensColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMemoryNodes queries the memory_nodes edge of a User.
func (c *UserClient) QueryMemoryNodes(_m *User) *MemoryNodeQuery {
	query := (&MemoryNodeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(memorynode.Table, memorynode.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.MemoryNodesTable, user.MemoryNodesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCards queries the cards edge of a User.
func (c *UserClient) QueryCards(_m *User) *CardQuery {
	query := (&CardClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(card.Table, card.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.CardsTable, user.CardsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCardItems queries the card_items edge of a User.
func (c *UserClient) QueryCardItems(_m *User) *CardItemQuery {
	query := (&CardItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(carditem.Table, carditem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.CardItemsTable, user.CardItemsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCardUserCounts queries the card_user_counts edge of a User.
func (c *UserClient) QueryCardUserCounts(_m *User) *CardUserCountQuery {
	query := (&CardUserCountClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(cardusercount.Table, cardusercount.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.CardUserCountsTable, user.CardUserCountsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCardUsers queries the card_users edge of a User.
func (c *UserClient) QueryCardUsers(_m *User) *CardUserQuery {
	query := (&CardUserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(carduser.Table, carduser.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.CardUsersTable, user.CardUsersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMemoryNodeUsers queries the memory_node_users edge of a User.
func (c *UserClient) QueryMemoryNodeUsers(_m *User) *MemoryNodeUserQuery {
	query := (&MemoryNodeUserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(memorynodeuser.Table, memorynodeuser.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.MemoryNodeUsersTable, user.MemoryNodeUsersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Card, CardItem, CardUser, CardUserCount, MemoryNode, MemoryNodeUser,
		RefreshToken, User []ent.Hook
	}
	inters struct {
		Card, CardItem, CardUser, CardUserCount, MemoryNode, MemoryNodeUser,
		RefreshToken, User []ent.Interceptor
	}
)
