// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/memoryguard/ent/memorynode"
	"arturgudiev/memoryguard/ent/schema"
	"arturgudiev/memoryguard/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemoryNodeCreate is the builder for creating a MemoryNode entity.
type MemoryNodeCreate struct {
	config
	mutation *MemoryNodeMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *MemoryNodeCreate) SetName(v string) *MemoryNodeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetChildren sets the "children" field.
func (_c *MemoryNodeCreate) SetChildren(v []int) *MemoryNodeCreate {
	_c.mutation.SetChildren(v)
	return _c
}

// SetParents sets the "parents" field.
func (_c *MemoryNodeCreate) SetParents(v []int) *MemoryNodeCreate {
	_c.mutation.SetParents(v)
	return _c
}

// SetCards sets the "cards" field.
func (_c *MemoryNodeCreate) SetCards(v []int) *MemoryNodeCreate {
	_c.mutation.SetCards(v)
	return _c
}

// SetAliases sets the "aliases" field.
func (_c *MemoryNodeCreate) SetAliases(v []string) *MemoryNodeCreate {
	_c.mutation.SetAliases(v)
	return _c
}

// SetPriorities sets the "priorities" field.
func (_c *MemoryNodeCreate) SetPriorities(v []schema.CardsPriority) *MemoryNodeCreate {
	_c.mutation.SetPriorities(v)
	return _c
}

// SetGroups sets the "groups" field.
func (_c *MemoryNodeCreate) SetGroups(v []schema.CardsGroup) *MemoryNodeCreate {
	_c.mutation.SetGroups(v)
	return _c
}

// SetShared sets the "shared" field.
func (_c *MemoryNodeCreate) SetShared(v bool) *MemoryNodeCreate {
	_c.mutation.SetShared(v)
	return _c
}

// SetNillableShared sets the "shared" field if the given value is not nil.
func (_c *MemoryNodeCreate) SetNillableShared(v *bool) *MemoryNodeCreate {
	if v != nil {
		_c.SetShared(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *MemoryNodeCreate) SetUserID(v int) *MemoryNodeCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *MemoryNodeCreate) SetID(v int) *MemoryNodeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *MemoryNodeCreate) SetUser(v *User) *MemoryNodeCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the MemoryNodeMutation object of the builder.
func (_c *MemoryNodeCreate) Mutation() *MemoryNodeMutation {
	return _c.mutation
}

// Save creates the MemoryNode in the database.
func (_c *MemoryNodeCreate) Save(ctx context.Context) (*MemoryNode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemoryNodeCreate) SaveX(ctx context.Context) *MemoryNode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoryNodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoryNodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MemoryNodeCreate) defaults() {
	if _, ok := _c.mutation.Children(); !ok {
		v := memorynode.DefaultChildren
		_c.mutation.SetChildren(v)
	}
	if _, ok := _c.mutation.Parents(); !ok {
		v := memorynode.DefaultParents
		_c.mutation.SetParents(v)
	}
	if _, ok := _c.mutation.Cards(); !ok {
		v := memorynode.DefaultCards
		_c.mutation.SetCards(v)
	}
	if _, ok := _c.mutation.Aliases(); !ok {
		v := memorynode.DefaultAliases
		_c.mutation.SetAliases(v)
	}
	if _, ok := _c.mutation.Shared(); !ok {
		v := memorynode.DefaultShared
		_c.mutation.SetShared(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemoryNodeCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "MemoryNode.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := memorynode.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MemoryNode.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Children(); !ok {
		return &ValidationError{Name: "children", err: errors.New(`ent: missing required field "MemoryNode.children"`)}
	}
	if _, ok := _c.mutation.Parents(); !ok {
		return &ValidationError{Name: "parents", err: errors.New(`ent: missing required field "MemoryNode.parents"`)}
	}
	if _, ok := _c.mutation.Cards(); !ok {
		return &ValidationError{Name: "cards", err: errors.New(`ent: missing required field "MemoryNode.cards"`)}
	}
	if _, ok := _c.mutation.Aliases(); !ok {
		return &ValidationError{Name: "aliases", err: errors.New(`ent: missing required field "MemoryNode.aliases"`)}
	}
	if _, ok := _c.mutation.Shared(); !ok {
		return &ValidationError{Name: "shared", err: errors.New(`ent: missing required field "MemoryNode.shared"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "MemoryNode.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := memorynode.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "MemoryNode.user_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := memorynode.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "MemoryNode.id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "MemoryNode.user"`)}
	}
	return nil
}

func (_c *MemoryNodeCreate) sqlSave(ctx context.Context) (*MemoryNode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemoryNodeCreate) createSpec() (*MemoryNode, *sqlgraph.CreateSpec) {
	var (
		_node = &MemoryNode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(memorynode.Table, sqlgraph.NewFieldSpec(memorynode.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(memorynode.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Children(); ok {
		_spec.SetField(memorynode.FieldChildren, field.TypeJSON, value)
		_node.Children = value
	}
	if value, ok := _c.mutation.Parents(); ok {
		_spec.SetField(memorynode.FieldParents, field.TypeJSON, value)
		_node.Parents = value
	}
	if value, ok := _c.mutation.Cards(); ok {
		_spec.SetField(memorynode.FieldCards, field.TypeJSON, value)
		_node.Cards = value
	}
	if value, ok := _c.mutation.Aliases(); ok {
		_spec.SetField(memorynode.FieldAliases, field.TypeJSON, value)
		_node.Aliases = value
	}
	if value, ok := _c.mutation.Priorities(); ok {
		_spec.SetField(memorynode.FieldPriorities, field.TypeJSON, value)
		_node.Priorities = value
	}
	if value, ok := _c.mutation.Groups(); ok {
		_spec.SetField(memorynode.FieldGroups, field.TypeJSON, value)
		_node.Groups = value
	}
	if value, ok := _c.mutation.Shared(); ok {
		_spec.SetField(memorynode.FieldShared, field.TypeBool, value)
		_node.Shared = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memorynode.UserTable,
			Columns: []string{memorynode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MemoryNodeCreateBulk is the builder for creating many MemoryNode entities in bulk.
type MemoryNodeCreateBulk struct {
	config
	err      error
	builders []*MemoryNodeCreate
}

// Save creates the MemoryNode entities in the database.
func (_c *MemoryNodeCreateBulk) Save(ctx context.Context) ([]*MemoryNode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MemoryNode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemoryNodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemoryNodeCreateBulk) SaveX(ctx context.Context) []*MemoryNode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoryNodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoryNodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
