// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/memoryguard/ent/memorynode"
	"arturgudiev/memoryguard/ent/schema"
	"arturgudiev/memoryguard/ent/user"
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// MemoryNode is the model entity for the MemoryNode schema.
type MemoryNode struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Children holds the value of the "children" field.
	Children []int `json:"children,omitempty"`
	// Parents holds the value of the "parents" field.
	Parents []int `json:"parents,omitempty"`
	// Cards holds the value of the "cards" field.
	Cards []int `json:"cards,omitempty"`
	// Aliases holds the value of the "aliases" field.
	Aliases []string `json:"aliases,omitempty"`
	// Priorities holds the value of the "priorities" field.
	Priorities []schema.CardsPriority `json:"priorities,omitempty"`
	// Groups holds the value of the "groups" field.
	Groups []schema.CardsGroup `json:"groups,omitempty"`
	// Shared holds the value of the "shared" field.
	Shared bool `json:"shared,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MemoryNodeQuery when eager-loading is set.
	Edges        MemoryNodeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MemoryNodeEdges holds the relations/edges for other nodes in the graph.
type MemoryNodeEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MemoryNodeEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MemoryNode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case memorynode.FieldChildren, memorynode.FieldParents, memorynode.FieldCards, memorynode.FieldAliases, memorynode.FieldPriorities, memorynode.FieldGroups:
			values[i] = new([]byte)
		case memorynode.FieldShared:
			values[i] = new(sql.NullBool)
		case memorynode.FieldID, memorynode.FieldUserID:
			values[i] = new(sql.NullInt64)
		case memorynode.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MemoryNode fields.
func (_m *MemoryNode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case memorynode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case memorynode.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case memorynode.FieldChildren:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field children", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Children); err != nil {
					return fmt.Errorf("unmarshal field children: %w", err)
				}
			}
		case memorynode.FieldParents:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field parents", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Parents); err != nil {
					return fmt.Errorf("unmarshal field parents: %w", err)
				}
			}
		case memorynode.FieldCards:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field cards", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Cards); err != nil {
					return fmt.Errorf("unmarshal field cards: %w", err)
				}
			}
		case memorynode.FieldAliases:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field aliases", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Aliases); err != nil {
					return fmt.Errorf("unmarshal field aliases: %w", err)
				}
			}
		case memorynode.FieldPriorities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field priorities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Priorities); err != nil {
					return fmt.Errorf("unmarshal field priorities: %w", err)
				}
			}
		case memorynode.FieldGroups:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field groups", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Groups); err != nil {
					return fmt.Errorf("unmarshal field groups: %w", err)
				}
			}
		case memorynode.FieldShared:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field shared", values[i])
			} else if value.Valid {
				_m.Shared = value.Bool
			}
		case memorynode.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MemoryNode.
// This includes values selected through modifiers, order, etc.
func (_m *MemoryNode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the MemoryNode entity.
func (_m *MemoryNode) QueryUser() *UserQuery {
	return NewMemoryNodeClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this MemoryNode.
// Note that you need to call MemoryNode.Unwrap() before calling this method if this MemoryNode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MemoryNode) Update() *MemoryNodeUpdateOne {
	return NewMemoryNodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MemoryNode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MemoryNode) Unwrap() *MemoryNode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MemoryNode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MemoryNode) String() string {
	var builder strings.Builder
	builder.WriteString("MemoryNode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("children=")
	builder.WriteString(fmt.Sprintf("%v", _m.Children))
	builder.WriteString(", ")
	builder.WriteString("parents=")
	builder.WriteString(fmt.Sprintf("%v", _m.Parents))
	builder.WriteString(", ")
	builder.WriteString("cards=")
	builder.WriteString(fmt.Sprintf("%v", _m.Cards))
	builder.WriteString(", ")
	builder.WriteString("aliases=")
	builder.WriteString(fmt.Sprintf("%v", _m.Aliases))
	builder.WriteString(", ")
	builder.WriteString("priorities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priorities))
	builder.WriteString(", ")
	builder.WriteString("groups=")
	builder.WriteString(fmt.Sprintf("%v", _m.Groups))
	builder.WriteString(", ")
	builder.WriteString("shared=")
	builder.WriteString(fmt.Sprintf("%v", _m.Shared))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteByte(')')
	return builder.String()
}

// MemoryNodes is a parsable slice of MemoryNode.
type MemoryNodes []*MemoryNode
