// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/memoryguard/ent/memorynode"
	"arturgudiev/memoryguard/ent/memorynodeuser"
	"arturgudiev/memoryguard/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemoryNodeUserCreate is the builder for creating a MemoryNodeUser entity.
type MemoryNodeUserCreate struct {
	config
	mutation *MemoryNodeUserMutation
	hooks    []Hook
}

// SetMemoryNodeID sets the "memory_node_id" field.
func (_c *MemoryNodeUserCreate) SetMemoryNodeID(v int) *MemoryNodeUserCreate {
	_c.mutation.SetMemoryNodeID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *MemoryNodeUserCreate) SetUserID(v int) *MemoryNodeUserCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *MemoryNodeUserCreate) SetID(v int) *MemoryNodeUserCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetMemoryNode sets the "memory_node" edge to the MemoryNode entity.
func (_c *MemoryNodeUserCreate) SetMemoryNode(v *MemoryNode) *MemoryNodeUserCreate {
	return _c.SetMemoryNodeID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *MemoryNodeUserCreate) SetUser(v *User) *MemoryNodeUserCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the MemoryNodeUserMutation object of the builder.
func (_c *MemoryNodeUserCreate) Mutation() *MemoryNodeUserMutation {
	return _c.mutation
}

// Save creates the MemoryNodeUser in the database.
func (_c *MemoryNodeUserCreate) Save(ctx context.Context) (*MemoryNodeUser, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemoryNodeUserCreate) SaveX(ctx context.Context) *MemoryNodeUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoryNodeUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoryNodeUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemoryNodeUserCreate) check() error {
	if _, ok := _c.mutation.MemoryNodeID(); !ok {
		return &ValidationError{Name: "memory_node_id", err: errors.New(`ent: missing required field "MemoryNodeUser.memory_node_id"`)}
	}
	if v, ok := _c.mutation.MemoryNodeID(); ok {
		if err := memorynodeuser.MemoryNodeIDValidator(v); err != nil {
			return &ValidationError{Name: "memory_node_id", err: fmt.Errorf(`ent: validator failed for field "MemoryNodeUser.memory_node_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "MemoryNodeUser.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := memorynodeuser.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "MemoryNodeUser.user_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := memorynodeuser.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "MemoryNodeUser.id": %w`, err)}
		}
	}
	if len(_c.mutation.MemoryNodeIDs()) == 0 {
		return &ValidationError{Name: "memory_node", err: errors.New(`ent: missing required edge "MemoryNodeUser.memory_node"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "MemoryNodeUser.user"`)}
	}
	return nil
}

func (_c *MemoryNodeUserCreate) sqlSave(ctx context.Context) (*MemoryNodeUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemoryNodeUserCreate) createSpec() (*MemoryNodeUser, *sqlgraph.CreateSpec) {
	var (
		_node = &MemoryNodeUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(memorynodeuser.Table, sqlgraph.NewFieldSpec(memorynodeuser.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if nodes := _c.mutation.MemoryNodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memorynodeuser.MemoryNodeTable,
			Columns: []string{memorynodeuser.MemoryNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memorynode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MemoryNodeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memorynodeuser.UserTable,
			Columns: []string{memorynodeuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MemoryNodeUserCreateBulk is the builder for creating many MemoryNodeUser entities in bulk.
type MemoryNodeUserCreateBulk struct {
	config
	err      error
	builders []*MemoryNodeUserCreate
}

// Save creates the MemoryNodeUser entities in the database.
func (_c *MemoryNodeUserCreateBulk) Save(ctx context.Context) ([]*MemoryNodeUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MemoryNodeUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemoryNodeUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemoryNodeUserCreateBulk) SaveX(ctx context.Context) []*MemoryNodeUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoryNodeUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoryNodeUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
