// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/memoryguard/ent/memorynode"
	"arturgudiev/memoryguard/ent/memorynodeuser"
	"arturgudiev/memoryguard/ent/predicate"
	"arturgudiev/memoryguard/ent/schema"
	"arturgudiev/memoryguard/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// MemoryNodeUpdate is the builder for updating MemoryNode entities.
type MemoryNodeUpdate struct {
	config
	hooks    []Hook
	mutation *MemoryNodeMutation
}

// Where appends a list predicates to the MemoryNodeUpdate builder.
func (_u *MemoryNodeUpdate) Where(ps ...predicate.MemoryNode) *MemoryNodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *MemoryNodeUpdate) SetName(v string) *MemoryNodeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MemoryNodeUpdate) SetNillableName(v *string) *MemoryNodeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetChildren sets the "children" field.
func (_u *MemoryNodeUpdate) SetChildren(v []int) *MemoryNodeUpdate {
	_u.mutation.SetChildren(v)
	return _u
}

// AppendChildren appends value to the "children" field.
func (_u *MemoryNodeUpdate) AppendChildren(v []int) *MemoryNodeUpdate {
	_u.mutation.AppendChildren(v)
	return _u
}

// SetParents sets the "parents" field.
func (_u *MemoryNodeUpdate) SetParents(v []int) *MemoryNodeUpdate {
	_u.mutation.SetParents(v)
	return _u
}

// AppendParents appends value to the "parents" field.
func (_u *MemoryNodeUpdate) AppendParents(v []int) *MemoryNodeUpdate {
	_u.mutation.AppendParents(v)
	return _u
}

// SetCards sets the "cards" field.
func (_u *MemoryNodeUpdate) SetCards(v []int) *MemoryNodeUpdate {
	_u.mutation.SetCards(v)
	return _u
}

// AppendCards appends value to the "cards" field.
func (_u *MemoryNodeUpdate) AppendCards(v []int) *MemoryNodeUpdate {
	_u.mutation.AppendCards(v)
	return _u
}

// SetAliases sets the "aliases" field.
func (_u *MemoryNodeUpdate) SetAliases(v []string) *MemoryNodeUpdate {
	_u.mutation.SetAliases(v)
	return _u
}

// AppendAliases appends value to the "aliases" field.
func (_u *MemoryNodeUpdate) AppendAliases(v []string) *MemoryNodeUpdate {
	_u.mutation.AppendAliases(v)
	return _u
}

// SetPriorities sets the "priorities" field.
func (_u *MemoryNodeUpdate) SetPriorities(v []schema.CardsPriority) *MemoryNodeUpdate {
	_u.mutation.SetPriorities(v)
	return _u
}

// AppendPriorities appends value to the "priorities" field.
func (_u *MemoryNodeUpdate) AppendPriorities(v []schema.CardsPriority) *MemoryNodeUpdate {
	_u.mutation.AppendPriorities(v)
	return _u
}

// ClearPriorities clears the value of the "priorities" field.
func (_u *MemoryNodeUpdate) ClearPriorities() *MemoryNodeUpdate {
	_u.mutation.ClearPriorities()
	return _u
}

// SetGroups sets the "groups" field.
func (_u *MemoryNodeUpdate) SetGroups(v []schema.CardsGroup) *MemoryNodeUpdate {
	_u.mutation.SetGroups(v)
	return _u
}

// AppendGroups appends value to the "groups" field.
func (_u *MemoryNodeUpdate) AppendGroups(v []schema.CardsGroup) *MemoryNodeUpdate {
	_u.mutation.AppendGroups(v)
	return _u
}

// ClearGroups clears the value of the "groups" field.
func (_u *MemoryNodeUpdate) ClearGroups() *MemoryNodeUpdate {
	_u.mutation.ClearGroups()
	return _u
}

// SetShared sets the "shared" field.
func (_u *MemoryNodeUpdate) SetShared(v bool) *MemoryNodeUpdate {
	_u.mutation.SetShared(v)
	return _u
}

// SetNillableShared sets the "shared" field if the given value is not nil.
func (_u *MemoryNodeUpdate) SetNillableShared(v *bool) *MemoryNodeUpdate {
	if v != nil {
		_u.SetShared(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MemoryNodeUpdate) SetUserID(v int) *MemoryNodeUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MemoryNodeUpdate) SetNillableUserID(v *int) *MemoryNodeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *MemoryNodeUpdate) SetUser(v *User) *MemoryNodeUpdate {
	return _u.SetUserID(v.ID)
}

// AddMemoryNodeUserIDs adds the "memory_node_users" edge to the MemoryNodeUser entity by IDs.
func (_u *MemoryNodeUpdate) AddMemoryNodeUserIDs(ids ...int) *MemoryNodeUpdate {
	_u.mutation.AddMemoryNodeUserIDs(ids...)
	return _u
}

// AddMemoryNodeUsers adds the "memory_node_users" edges to the MemoryNodeUser entity.
func (_u *MemoryNodeUpdate) AddMemoryNodeUsers(v ...*MemoryNodeUser) *MemoryNodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemoryNodeUserIDs(ids...)
}

// Mutation returns the MemoryNodeMutation object of the builder.
func (_u *MemoryNodeUpdate) Mutation() *MemoryNodeMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MemoryNodeUpdate) ClearUser() *MemoryNodeUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearMemoryNodeUsers clears all "memory_node_users" edges to the MemoryNodeUser entity.
func (_u *MemoryNodeUpdate) ClearMemoryNodeUsers() *MemoryNodeUpdate {
	_u.mutation.ClearMemoryNodeUsers()
	return _u
}

// RemoveMemoryNodeUserIDs removes the "memory_node_users" edge to MemoryNodeUser entities by IDs.
func (_u *MemoryNodeUpdate) RemoveMemoryNodeUserIDs(ids ...int) *MemoryNodeUpdate {
	_u.mutation.RemoveMemoryNodeUserIDs(ids...)
	return _u
}

// RemoveMemoryNodeUsers removes "memory_node_users" edges to MemoryNodeUser entities.
func (_u *MemoryNodeUpdate) RemoveMemoryNodeUsers(v ...*MemoryNodeUser) *MemoryNodeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemoryNodeUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemoryNodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemoryNodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemoryNodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemoryNodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemoryNodeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := memorynode.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MemoryNode.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := memorynode.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "MemoryNode.user_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MemoryNode.user"`)
	}
	return nil
}

func (_u *MemoryNodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memorynode.Table, memorynode.Columns, sqlgraph.NewFieldSpec(memorynode.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(memorynode.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Children(); ok {
		_spec.SetField(memorynode.FieldChildren, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedChildren(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, memorynode.FieldChildren, value)
		})
	}
	if value, ok := _u.mutation.Parents(); ok {
		_spec.SetField(memorynode.FieldParents, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedParents(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, memorynode.FieldParents, value)
		})
	}
	if value, ok := _u.mutation.Cards(); ok {
		_spec.SetField(memorynode.FieldCards, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCards(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, memorynode.FieldCards, value)
		})
	}
	if value, ok := _u.mutation.Aliases(); ok {
		_spec.SetField(memorynode.FieldAliases, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAliases(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, memorynode.FieldAliases, value)
		})
	}
	if value, ok := _u.mutation.Priorities(); ok {
		_spec.SetField(memorynode.FieldPriorities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPriorities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, memorynode.FieldPriorities, value)
		})
	}
	if _u.mutation.PrioritiesCleared() {
		_spec.ClearField(memorynode.FieldPriorities, field.TypeJSON)
	}
	if value, ok := _u.mutation.Groups(); ok {
		_spec.SetField(memorynode.FieldGroups, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGroups(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, memorynode.FieldGroups, value)
		})
	}
	if _u.mutation.GroupsCleared() {
		_spec.ClearField(memorynode.FieldGroups, field.TypeJSON)
	}
	if value, ok := _u.mutation.Shared(); ok {
		_spec.SetField(memorynode.FieldShared, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memorynode.UserTable,
			Columns: []string{memorynode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memorynode.UserTable,
			Columns: []string{memorynode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemoryNodeUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memorynode.MemoryNodeUsersTable,
			Columns: []string{memorynode.MemoryNodeUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memorynodeuser.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemoryNodeUsersIDs(); len(nodes) > 0 && !_u.mutation.MemoryNodeUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memorynode.MemoryNodeUsersTable,
			Columns: []string{memorynode.MemoryNodeUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memorynodeuser.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemoryNodeUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memorynode.MemoryNodeUsersTable,
			Columns: []string{memorynode.MemoryNodeUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memorynodeuser.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memorynode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemoryNodeUpdateOne is the builder for updating a single MemoryNode entity.
type MemoryNodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemoryNodeMutation
}

// SetName sets the "name" field.
func (_u *MemoryNodeUpdateOne) SetName(v string) *MemoryNodeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MemoryNodeUpdateOne) SetNillableName(v *string) *MemoryNodeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetChildren sets the "children" field.
func (_u *MemoryNodeUpdateOne) SetChildren(v []int) *MemoryNodeUpdateOne {
	_u.mutation.SetChildren(v)
	return _u
}

// AppendChildren appends value to the "children" field.
func (_u *MemoryNodeUpdateOne) AppendChildren(v []int) *MemoryNodeUpdateOne {
	_u.mutation.AppendChildren(v)
	return _u
}

// SetParents sets the "parents" field.
func (_u *MemoryNodeUpdateOne) SetParents(v []int) *MemoryNodeUpdateOne {
	_u.mutation.SetParents(v)
	return _u
}

// AppendParents appends value to the "parents" field.
func (_u *MemoryNodeUpdateOne) AppendParents(v []int) *MemoryNodeUpdateOne {
	_u.mutation.AppendParents(v)
	return _u
}

// SetCards sets the "cards" field.
func (_u *MemoryNodeUpdateOne) SetCards(v []int) *MemoryNodeUpdateOne {
	_u.mutation.SetCards(v)
	return _u
}

// AppendCards appends value to the "cards" field.
func (_u *MemoryNodeUpdateOne) AppendCards(v []int) *MemoryNodeUpdateOne {
	_u.mutation.AppendCards(v)
	return _u
}

// SetAliases sets the "aliases" field.
func (_u *MemoryNodeUpdateOne) SetAliases(v []string) *MemoryNodeUpdateOne {
	_u.mutation.SetAliases(v)
	return _u
}

// AppendAliases appends value to the "aliases" field.
func (_u *MemoryNodeUpdateOne) AppendAliases(v []string) *MemoryNodeUpdateOne {
	_u.mutation.AppendAliases(v)
	return _u
}

// SetPriorities sets the "priorities" field.
func (_u *MemoryNodeUpdateOne) SetPriorities(v []schema.CardsPriority) *MemoryNodeUpdateOne {
	_u.mutation.SetPriorities(v)
	return _u
}

// AppendPriorities appends value to the "priorities" field.
func (_u *MemoryNodeUpdateOne) AppendPriorities(v []schema.CardsPriority) *MemoryNodeUpdateOne {
	_u.mutation.AppendPriorities(v)
	return _u
}

// ClearPriorities clears the value of the "priorities" field.
func (_u *MemoryNodeUpdateOne) ClearPriorities() *MemoryNodeUpdateOne {
	_u.mutation.ClearPriorities()
	return _u
}

// SetGroups sets the "groups" field.
func (_u *MemoryNodeUpdateOne) SetGroups(v []schema.CardsGroup) *MemoryNodeUpdateOne {
	_u.mutation.SetGroups(v)
	return _u
}

// AppendGroups appends value to the "groups" field.
func (_u *MemoryNodeUpdateOne) AppendGroups(v []schema.CardsGroup) *MemoryNodeUpdateOne {
	_u.mutation.AppendGroups(v)
	return _u
}

// ClearGroups clears the value of the "groups" field.
func (_u *MemoryNodeUpdateOne) ClearGroups() *MemoryNodeUpdateOne {
	_u.mutation.ClearGroups()
	return _u
}

// SetShared sets the "shared" field.
func (_u *MemoryNodeUpdateOne) SetShared(v bool) *MemoryNodeUpdateOne {
	_u.mutation.SetShared(v)
	return _u
}

// SetNillableShared sets the "shared" field if the given value is not nil.
func (_u *MemoryNodeUpdateOne) SetNillableShared(v *bool) *MemoryNodeUpdateOne {
	if v != nil {
		_u.SetShared(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MemoryNodeUpdateOne) SetUserID(v int) *MemoryNodeUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MemoryNodeUpdateOne) SetNillableUserID(v *int) *MemoryNodeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *MemoryNodeUpdateOne) SetUser(v *User) *MemoryNodeUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddMemoryNodeUserIDs adds the "memory_node_users" edge to the MemoryNodeUser entity by IDs.
func (_u *MemoryNodeUpdateOne) AddMemoryNodeUserIDs(ids ...int) *MemoryNodeUpdateOne {
	_u.mutation.AddMemoryNodeUserIDs(ids...)
	return _u
}

// AddMemoryNodeUsers adds the "memory_node_users" edges to the MemoryNodeUser entity.
func (_u *MemoryNodeUpdateOne) AddMemoryNodeUsers(v ...*MemoryNodeUser) *MemoryNodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemoryNodeUserIDs(ids...)
}

// Mutation returns the MemoryNodeMutation object of the builder.
func (_u *MemoryNodeUpdateOne) Mutation() *MemoryNodeMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MemoryNodeUpdateOne) ClearUser() *MemoryNodeUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearMemoryNodeUsers clears all "memory_node_users" edges to the MemoryNodeUser entity.
func (_u *MemoryNodeUpdateOne) ClearMemoryNodeUsers() *MemoryNodeUpdateOne {
	_u.mutation.ClearMemoryNodeUsers()
	return _u
}

// RemoveMemoryNodeUserIDs removes the "memory_node_users" edge to MemoryNodeUser entities by IDs.
func (_u *MemoryNodeUpdateOne) RemoveMemoryNodeUserIDs(ids ...int) *MemoryNodeUpdateOne {
	_u.mutation.RemoveMemoryNodeUserIDs(ids...)
	return _u
}

// RemoveMemoryNodeUsers removes "memory_node_users" edges to MemoryNodeUser entities.
func (_u *MemoryNodeUpdateOne) RemoveMemoryNodeUsers(v ...*MemoryNodeUser) *MemoryNodeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemoryNodeUserIDs(ids...)
}

// Where appends a list predicates to the MemoryNodeUpdate builder.
func (_u *MemoryNodeUpdateOne) Where(ps ...predicate.MemoryNode) *MemoryNodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemoryNodeUpdateOne) Select(field string, fields ...string) *MemoryNodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MemoryNode entity.
func (_u *MemoryNodeUpdateOne) Save(ctx context.Context) (*MemoryNode, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemoryNodeUpdateOne) SaveX(ctx context.Context) *MemoryNode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemoryNodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemoryNodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemoryNodeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := memorynode.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MemoryNode.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := memorynode.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "MemoryNode.user_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MemoryNode.user"`)
	}
	return nil
}

func (_u *MemoryNodeUpdateOne) sqlSave(ctx context.Context) (_node *MemoryNode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memorynode.Table, memorynode.Columns, sqlgraph.NewFieldSpec(memorynode.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MemoryNode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memorynode.FieldID)
		for _, f := range fields {
			if !memorynode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != memorynode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(memorynode.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Children(); ok {
		_spec.SetField(memorynode.FieldChildren, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedChildren(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, memorynode.FieldChildren, value)
		})
	}
	if value, ok := _u.mutation.Parents(); ok {
		_spec.SetField(memorynode.FieldParents, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedParents(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, memorynode.FieldParents, value)
		})
	}
	if value, ok := _u.mutation.Cards(); ok {
		_spec.SetField(memorynode.FieldCards, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCards(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, memorynode.FieldCards, value)
		})
	}
	if value, ok := _u.mutation.Aliases(); ok {
		_spec.SetField(memorynode.FieldAliases, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAliases(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, memorynode.FieldAliases, value)
		})
	}
	if value, ok := _u.mutation.Priorities(); ok {
		_spec.SetField(memorynode.FieldPriorities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPriorities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, memorynode.FieldPriorities, value)
		})
	}
	if _u.mutation.PrioritiesCleared() {
		_spec.ClearField(memorynode.FieldPriorities, field.TypeJSON)
	}
	if value, ok := _u.mutation.Groups(); ok {
		_spec.SetField(memorynode.FieldGroups, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGroups(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, memorynode.FieldGroups, value)
		})
	}
	if _u.mutation.GroupsCleared() {
		_spec.ClearField(memorynode.FieldGroups, field.TypeJSON)
	}
	if value, ok := _u.mutation.Shared(); ok {
		_spec.SetField(memorynode.FieldShared, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memorynode.UserTable,
			Columns: []string{memorynode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memorynode.UserTable,
			Columns: []string{memorynode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemoryNodeUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memorynode.MemoryNodeUsersTable,
			Columns: []string{memorynode.MemoryNodeUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memorynodeuser.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemoryNodeUsersIDs(); len(nodes) > 0 && !_u.mutation.MemoryNodeUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memorynode.MemoryNodeUsersTable,
			Columns: []string{memorynode.MemoryNodeUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memorynodeuser.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemoryNodeUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memorynode.MemoryNodeUsersTable,
			Columns: []string{memorynode.MemoryNodeUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memorynodeuser.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MemoryNode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memorynode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
