// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/memoryguard/ent/memorynodeuser"
	"arturgudiev/memoryguard/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemoryNodeUserDelete is the builder for deleting a MemoryNodeUser entity.
type MemoryNodeUserDelete struct {
	config
	hooks    []Hook
	mutation *MemoryNodeUserMutation
}

// Where appends a list predicates to the MemoryNodeUserDelete builder.
func (_d *MemoryNodeUserDelete) Where(ps ...predicate.MemoryNodeUser) *MemoryNodeUserDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MemoryNodeUserDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MemoryNodeUserDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MemoryNodeUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(memorynodeuser.Table, sqlgraph.NewFieldSpec(memorynodeuser.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MemoryNodeUserDeleteOne is the builder for deleting a single MemoryNodeUser entity.
type MemoryNodeUserDeleteOne struct {
	_d *MemoryNodeUserDelete
}

// Where appends a list predicates to the MemoryNodeUserDelete builder.
func (_d *MemoryNodeUserDeleteOne) Where(ps ...predicate.MemoryNodeUser) *MemoryNodeUserDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MemoryNodeUserDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{memorynodeuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MemoryNodeUserDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
