// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/memoryguard/ent/card"
	"arturgudiev/memoryguard/ent/carditem"
	"arturgudiev/memoryguard/ent/carduser"
	"arturgudiev/memoryguard/ent/cardusercount"
	"arturgudiev/memoryguard/ent/memorynode"
	"arturgudiev/memoryguard/ent/memorynodeuser"
	"arturgudiev/memoryguard/ent/refreshtoken"
	"arturgudiev/memoryguard/ent/schema"
	"arturgudiev/memoryguard/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cardFields := schema.Card{}.Fields()
	_ = cardFields
	// cardDescQuestion is the schema descriptor for question field.
	cardDescQuestion := cardFields[1].Descriptor()
	// card.DefaultQuestion holds the default value on creation for the question field.
	card.DefaultQuestion = cardDescQuestion.Default.([]int)
	// cardDescAnswer is the schema descriptor for answer field.
	cardDescAnswer := cardFields[2].Descriptor()
	// card.DefaultAnswer holds the default value on creation for the answer field.
	card.DefaultAnswer = cardDescAnswer.Default.([]int)
	// cardDescParentNodes is the schema descriptor for parent_nodes field.
	cardDescParentNodes := cardFields[3].Descriptor()
	// card.DefaultParentNodes holds the default value on creation for the parent_nodes field.
	card.DefaultParentNodes = cardDescParentNodes.Default.([]int)
	// cardDescUsed is the schema descriptor for used field.
	cardDescUsed := cardFields[4].Descriptor()
	// card.DefaultUsed holds the default value on creation for the used field.
	card.DefaultUsed = cardDescUsed.Default.(int)
	// cardDescNeeded is the schema descriptor for needed field.
	cardDescNeeded := cardFields[5].Descriptor()
	// card.DefaultNeeded holds the default value on creation for the needed field.
	card.DefaultNeeded = cardDescNeeded.Default.(int)
	// cardDescCount is the schema descriptor for count field.
	cardDescCount := cardFields[6].Descriptor()
	// card.DefaultCount holds the default value on creation for the count field.
	card.DefaultCount = cardDescCount.Default.(int)
	// cardDescReverseCount is the schema descriptor for reverse_count field.
	cardDescReverseCount := cardFields[7].Descriptor()
	// card.DefaultReverseCount holds the default value on creation for the reverse_count field.
	card.DefaultReverseCount = cardDescReverseCount.Default.(int)
	// cardDescShared is the schema descriptor for shared field.
	cardDescShared := cardFields[9].Descriptor()
	// card.DefaultShared holds the default value on creation for the shared field.
	card.DefaultShared = cardDescShared.Default.(bool)
	// cardDescUserID is the schema descriptor for user_id field.
	cardDescUserID := cardFields[10].Descriptor()
	// card.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	card.UserIDValidator = cardDescUserID.Validators[0].(func(int) error)
	// cardDescID is the schema descriptor for id field.
	cardDescID := cardFields[0].Descriptor()
	// card.IDValidator is a validator for the "id" field. It is called by the builders before save.
	card.IDValidator = cardDescID.Validators[0].(func(int) error)
	carditemFields := schema.CardItem{}.Fields()
	_ = carditemFields
	// carditemDescShared is the schema descriptor for shared field.
	carditemDescShared := carditemFields[9].Descriptor()
	// carditem.DefaultShared holds the default value on creation for the shared field.
	carditem.DefaultShared = carditemDescShared.Default.(bool)
	// carditemDescUserID is the schema descriptor for user_id field.
	carditemDescUserID := carditemFields[10].Descriptor()
	// carditem.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	carditem.UserIDValidator = carditemDescUserID.Validators[0].(func(int) error)
	// carditemDescID is the schema descriptor for id field.
	carditemDescID := carditemFields[0].Descriptor()
	// carditem.IDValidator is a validator for the "id" field. It is called by the builders before save.
	carditem.IDValidator = carditemDescID.Validators[0].(func(int) error)
	carduserFields := schema.CardUser{}.Fields()
	_ = carduserFields
	// carduserDescCardID is the schema descriptor for card_id field.
	carduserDescCardID := carduserFields[1].Descriptor()
	// carduser.CardIDValidator is a validator for the "card_id" field. It is called by the builders before save.
	carduser.CardIDValidator = carduserDescCardID.Validators[0].(func(int) error)
	// carduserDescUserID is the schema descriptor for user_id field.
	carduserDescUserID := carduserFields[2].Descriptor()
	// carduser.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	carduser.UserIDValidator = carduserDescUserID.Validators[0].(func(int) error)
	// carduserDescID is the schema descriptor for id field.
	carduserDescID := carduserFields[0].Descriptor()
	// carduser.IDValidator is a validator for the "id" field. It is called by the builders before save.
	carduser.IDValidator = carduserDescID.Validators[0].(func(int) error)
	cardusercountFields := schema.CardUserCount{}.Fields()
	_ = cardusercountFields
	// cardusercountDescCardID is the schema descriptor for card_id field.
	cardusercountDescCardID := cardusercountFields[1].Descriptor()
	// cardusercount.CardIDValidator is a validator for the "card_id" field. It is called by the builders before save.
	cardusercount.CardIDValidator = cardusercountDescCardID.Validators[0].(func(int) error)
	// cardusercountDescUserID is the schema descriptor for user_id field.
	cardusercountDescUserID := cardusercountFields[2].Descriptor()
	// cardusercount.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	cardusercount.UserIDValidator = cardusercountDescUserID.Validators[0].(func(int) error)
	// cardusercountDescCount is the schema descriptor for count field.
	cardusercountDescCount := cardusercountFields[3].Descriptor()
	// cardusercount.DefaultCount holds the default value on creation for the count field.
	cardusercount.DefaultCount = cardusercountDescCount.Default.(int)
	// cardusercountDescID is the schema descriptor for id field.
	cardusercountDescID := cardusercountFields[0].Descriptor()
	// cardusercount.IDValidator is a validator for the "id" field. It is called by the builders before save.
	cardusercount.IDValidator = cardusercountDescID.Validators[0].(func(int) error)
	memorynodeFields := schema.MemoryNode{}.Fields()
	_ = memorynodeFields
	// memorynodeDescName is the schema descriptor for name field.
	memorynodeDescName := memorynodeFields[1].Descriptor()
	// memorynode.NameValidator is a validator for the "name" field. It is called by the builders before save.
	memorynode.NameValidator = memorynodeDescName.Validators[0].(func(string) error)
	// memorynodeDescDescription is the schema descriptor for description field.
	memorynodeDescDescription := memorynodeFields[2].Descriptor()
	// memorynode.DefaultDescription holds the default value on creation for the description field.
	memorynode.DefaultDescription = memorynodeDescDescription.Default.(string)
	// memorynodeDescChildren is the schema descriptor for children field.
	memorynodeDescChildren := memorynodeFields[3].Descriptor()
	// memorynode.DefaultChildren holds the default value on creation for the children field.
	memorynode.DefaultChildren = memorynodeDescChildren.Default.([]int)
	// memorynodeDescParents is the schema descriptor for parents field.
	memorynodeDescParents := memorynodeFields[4].Descriptor()
	// memorynode.DefaultParents holds the default value on creation for the parents field.
	memorynode.DefaultParents = memorynodeDescParents.Default.([]int)
	// memorynodeDescCards is the schema descriptor for cards field.
	memorynodeDescCards := memorynodeFields[5].Descriptor()
	// memorynode.DefaultCards holds the default value on creation for the cards field.
	memorynode.DefaultCards = memorynodeDescCards.Default.([]int)
	// memorynodeDescAliases is the schema descriptor for aliases field.
	memorynodeDescAliases := memorynodeFields[6].Descriptor()
	// memorynode.DefaultAliases holds the default value on creation for the aliases field.
	memorynode.DefaultAliases = memorynodeDescAliases.Default.([]string)
	// memorynodeDescShared is the schema descriptor for shared field.
	memorynodeDescShared := memorynodeFields[9].Descriptor()
	// memorynode.DefaultShared holds the default value on creation for the shared field.
	memorynode.DefaultShared = memorynodeDescShared.Default.(bool)
	// memorynodeDescUserID is the schema descriptor for user_id field.
	memorynodeDescUserID := memorynodeFields[10].Descriptor()
	// memorynode.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	memorynode.UserIDValidator = memorynodeDescUserID.Validators[0].(func(int) error)
	// memorynodeDescID is the schema descriptor for id field.
	memorynodeDescID := memorynodeFields[0].Descriptor()
	// memorynode.IDValidator is a validator for the "id" field. It is called by the builders before save.
	memorynode.IDValidator = memorynodeDescID.Validators[0].(func(int) error)
	memorynodeuserFields := schema.MemoryNodeUser{}.Fields()
	_ = memorynodeuserFields
	// memorynodeuserDescMemoryNodeID is the schema descriptor for memory_node_id field.
	memorynodeuserDescMemoryNodeID := memorynodeuserFields[1].Descriptor()
	// memorynodeuser.MemoryNodeIDValidator is a validator for the "memory_node_id" field. It is called by the builders before save.
	memorynodeuser.MemoryNodeIDValidator = memorynodeuserDescMemoryNodeID.Validators[0].(func(int) error)
	// memorynodeuserDescUserID is the schema descriptor for user_id field.
	memorynodeuserDescUserID := memorynodeuserFields[2].Descriptor()
	// memorynodeuser.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	memorynodeuser.UserIDValidator = memorynodeuserDescUserID.Validators[0].(func(int) error)
	// memorynodeuserDescID is the schema descriptor for id field.
	memorynodeuserDescID := memorynodeuserFields[0].Descriptor()
	// memorynodeuser.IDValidator is a validator for the "id" field. It is called by the builders before save.
	memorynodeuser.IDValidator = memorynodeuserDescID.Validators[0].(func(int) error)
	refreshtokenFields := schema.RefreshToken{}.Fields()
	_ = refreshtokenFields
	// refreshtokenDescUserID is the schema descriptor for user_id field.
	refreshtokenDescUserID := refreshtokenFields[1].Descriptor()
	// refreshtoken.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	refreshtoken.UserIDValidator = refreshtokenDescUserID.Validators[0].(func(int) error)
	// refreshtokenDescCreatedAt is the schema descriptor for created_at field.
	refreshtokenDescCreatedAt := refreshtokenFields[4].Descriptor()
	// refreshtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	refreshtoken.DefaultCreatedAt = refreshtokenDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescLogin is the schema descriptor for login field.
	userDescLogin := userFields[2].Descriptor()
	// user.LoginValidator is a validator for the "login" field. It is called by the builders before save.
	user.LoginValidator = userDescLogin.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[3].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[4].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(int) error)
}
