// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/memoryguard/ent/schema"
	"arturgudiev/memoryguard/ent/user"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Login holds the value of the "login" field.
	Login string `json:"login,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"-"`
	// Role holds the value of the "role" field.
	Role schema.UserRole `json:"role,omitempty"`
	// Verified holds the value of the "verified" field.
	Verified bool `json:"verified,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// RefreshTokens holds the value of the refresh_tokens edge.
	RefreshTokens []*RefreshToken `json:"refresh_tokens,omitempty"`
	// MemoryNodes holds the value of the memory_nodes edge.
	MemoryNodes []*MemoryNode `json:"memory_nodes,omitempty"`
	// Cards holds the value of the cards edge.
	Cards []*Card `json:"cards,omitempty"`
	// CardItems holds the value of the card_items edge.
	CardItems []*CardItem `json:"card_items,omitempty"`
	// CardUserCounts holds the value of the card_user_counts edge.
	CardUserCounts []*CardUserCount `json:"card_user_counts,omitempty"`
	// CardUsers holds the value of the card_users edge.
	CardUsers []*CardUser `json:"card_users,omitempty"`
	// MemoryNodeUsers holds the value of the memory_node_users edge.
	MemoryNodeUsers []*MemoryNodeUser `json:"memory_node_users,omitempty"`
	// VerificationCodes holds the value of the verification_codes edge.
	VerificationCodes []*VerificationCode `json:"verification_codes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [8]bool
}

// RefreshTokensOrErr returns the RefreshTokens value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) RefreshTokensOrErr() ([]*RefreshToken, error) {
	if e.loadedTypes[0] {
		return e.RefreshTokens, nil
	}
	return nil, &NotLoadedError{edge: "refresh_tokens"}
}

// MemoryNodesOrErr returns the MemoryNodes value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) MemoryNodesOrErr() ([]*MemoryNode, error) {
	if e.loadedTypes[1] {
		return e.MemoryNodes, nil
	}
	return nil, &NotLoadedError{edge: "memory_nodes"}
}

// CardsOrErr returns the Cards value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CardsOrErr() ([]*Card, error) {
	if e.loadedTypes[2] {
		return e.Cards, nil
	}
	return nil, &NotLoadedError{edge: "cards"}
}

// CardItemsOrErr returns the CardItems value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CardItemsOrErr() ([]*CardItem, error) {
	if e.loadedTypes[3] {
		return e.CardItems, nil
	}
	return nil, &NotLoadedError{edge: "card_items"}
}

// CardUserCountsOrErr returns the CardUserCounts value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CardUserCountsOrErr() ([]*CardUserCount, error) {
	if e.loadedTypes[4] {
		return e.CardUserCounts, nil
	}
	return nil, &NotLoadedError{edge: "card_user_counts"}
}

// CardUsersOrErr returns the CardUsers value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CardUsersOrErr() ([]*CardUser, error) {
	if e.loadedTypes[5] {
		return e.CardUsers, nil
	}
	return nil, &NotLoadedError{edge: "card_users"}
}

// MemoryNodeUsersOrErr returns the MemoryNodeUsers value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) MemoryNodeUsersOrErr() ([]*MemoryNodeUser, error) {
	if e.loadedTypes[6] {
		return e.MemoryNodeUsers, nil
	}
	return nil, &NotLoadedError{edge: "memory_node_users"}
}

// VerificationCodesOrErr returns the VerificationCodes value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) VerificationCodesOrErr() ([]*VerificationCode, error) {
	if e.loadedTypes[7] {
		return e.VerificationCodes, nil
	}
	return nil, &NotLoadedError{edge: "verification_codes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldVerified:
			values[i] = new(sql.NullBool)
		case user.FieldID:
			values[i] = new(sql.NullInt64)
		case user.FieldName, user.FieldLogin, user.FieldEmail, user.FieldPasswordHash, user.FieldRole:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case user.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case user.FieldLogin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field login", values[i])
			} else if value.Valid {
				_m.Login = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		case user.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = schema.UserRole(value.String)
			}
		case user.FieldVerified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field verified", values[i])
			} else if value.Valid {
				_m.Verified = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRefreshTokens queries the "refresh_tokens" edge of the User entity.
func (_m *User) QueryRefreshTokens() *RefreshTokenQuery {
	return NewUserClient(_m.config).QueryRefreshTokens(_m)
}

// QueryMemoryNodes queries the "memory_nodes" edge of the User entity.
func (_m *User) QueryMemoryNodes() *MemoryNodeQuery {
	return NewUserClient(_m.config).QueryMemoryNodes(_m)
}

// QueryCards queries the "cards" edge of the User entity.
func (_m *User) QueryCards() *CardQuery {
	return NewUserClient(_m.config).QueryCards(_m)
}

// QueryCardItems queries the "card_items" edge of the User entity.
func (_m *User) QueryCardItems() *CardItemQuery {
	return NewUserClient(_m.config).QueryCardItems(_m)
}

// QueryCardUserCounts queries the "card_user_counts" edge of the User entity.
func (_m *User) QueryCardUserCounts() *CardUserCountQuery {
	return NewUserClient(_m.config).QueryCardUserCounts(_m)
}

// QueryCardUsers queries the "card_users" edge of the User entity.
func (_m *User) QueryCardUsers() *CardUserQuery {
	return NewUserClient(_m.config).QueryCardUsers(_m)
}

// QueryMemoryNodeUsers queries the "memory_node_users" edge of the User entity.
func (_m *User) QueryMemoryNodeUsers() *MemoryNodeUserQuery {
	return NewUserClient(_m.config).QueryMemoryNodeUsers(_m)
}

// QueryVerificationCodes queries the "verification_codes" edge of the User entity.
func (_m *User) QueryVerificationCodes() *VerificationCodeQuery {
	return NewUserClient(_m.config).QueryVerificationCodes(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("login=")
	builder.WriteString(_m.Login)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("password_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", _m.Role))
	builder.WriteString(", ")
	builder.WriteString("verified=")
	builder.WriteString(fmt.Sprintf("%v", _m.Verified))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
