// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/memoryguard/ent/predicate"
	"arturgudiev/memoryguard/ent/user"
	"arturgudiev/memoryguard/ent/verificationcode"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VerificationCodeUpdate is the builder for updating VerificationCode entities.
type VerificationCodeUpdate struct {
	config
	hooks    []Hook
	mutation *VerificationCodeMutation
}

// Where appends a list predicates to the VerificationCodeUpdate builder.
func (_u *VerificationCodeUpdate) Where(ps ...predicate.VerificationCode) *VerificationCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *VerificationCodeUpdate) SetUserID(v int) *VerificationCodeUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *VerificationCodeUpdate) SetNillableUserID(v *int) *VerificationCodeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *VerificationCodeUpdate) SetCode(v string) *VerificationCodeUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *VerificationCodeUpdate) SetNillableCode(v *string) *VerificationCodeUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *VerificationCodeUpdate) SetExpiresAt(v time.Time) *VerificationCodeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *VerificationCodeUpdate) SetNillableExpiresAt(v *time.Time) *VerificationCodeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *VerificationCodeUpdate) SetUser(v *User) *VerificationCodeUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the VerificationCodeMutation object of the builder.
func (_u *VerificationCodeUpdate) Mutation() *VerificationCodeMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *VerificationCodeUpdate) ClearUser() *VerificationCodeUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VerificationCodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VerificationCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VerificationCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VerificationCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VerificationCodeUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := verificationcode.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "VerificationCode.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := verificationcode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "VerificationCode.code": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VerificationCode.user"`)
	}
	return nil
}

func (_u *VerificationCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(verificationcode.Table, verificationcode.Columns, sqlgraph.NewFieldSpec(verificationcode.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(verificationcode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(verificationcode.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   verificationcode.UserTable,
			Columns: []string{verificationcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   verificationcode.UserTable,
			Columns: []string{verificationcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{verificationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VerificationCodeUpdateOne is the builder for updating a single VerificationCode entity.
type VerificationCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VerificationCodeMutation
}

// SetUserID sets the "user_id" field.
func (_u *VerificationCodeUpdateOne) SetUserID(v int) *VerificationCodeUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *VerificationCodeUpdateOne) SetNillableUserID(v *int) *VerificationCodeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *VerificationCodeUpdateOne) SetCode(v string) *VerificationCodeUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *VerificationCodeUpdateOne) SetNillableCode(v *string) *VerificationCodeUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *VerificationCodeUpdateOne) SetExpiresAt(v time.Time) *VerificationCodeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *VerificationCodeUpdateOne) SetNillableExpiresAt(v *time.Time) *VerificationCodeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *VerificationCodeUpdateOne) SetUser(v *User) *VerificationCodeUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the VerificationCodeMutation object of the builder.
func (_u *VerificationCodeUpdateOne) Mutation() *VerificationCodeMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *VerificationCodeUpdateOne) ClearUser() *VerificationCodeUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the VerificationCodeUpdate builder.
func (_u *VerificationCodeUpdateOne) Where(ps ...predicate.VerificationCode) *VerificationCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VerificationCodeUpdateOne) Select(field string, fields ...string) *VerificationCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VerificationCode entity.
func (_u *VerificationCodeUpdateOne) Save(ctx context.Context) (*VerificationCode, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VerificationCodeUpdateOne) SaveX(ctx context.Context) *VerificationCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VerificationCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VerificationCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VerificationCodeUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := verificationcode.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "VerificationCode.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := verificationcode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "VerificationCode.code": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VerificationCode.user"`)
	}
	return nil
}

func (_u *VerificationCodeUpdateOne) sqlSave(ctx context.Context) (_node *VerificationCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(verificationcode.Table, verificationcode.Columns, sqlgraph.NewFieldSpec(verificationcode.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VerificationCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, verificationcode.FieldID)
		for _, f := range fields {
			if !verificationcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != verificationcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(verificationcode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(verificationcode.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   verificationcode.UserTable,
			Columns: []string{verificationcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   verificationcode.UserTable,
			Columns: []string{verificationcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &VerificationCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{verificationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
